### ISSUE TITLE
root page copy when not signed in

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#129]
Hey @imaginista,
We need your magic. You had mentioned incorporating some landing page copy letting folks know that the application is in beta. Can you cook up some introductory copy that covers the concerns you mentioned?

**Comment by imaginista** [comment]
From what I understand, you can't actually load the application without first logging in/signing up. So I think we can add "BETA" on the landing page, then somewhere in-app. I've attached a mock of two versions (light & dark) of how the landing page could look. The image of the people you see is a static shot of a looping video.

Dark
![landingpage](https://cloud.githubusercontent.com/assets/1500663/25906037/9e40122a-3571-11e7-9695-50dba4b3895d.png)

Light
![Uploading landingPage light.png…]()

**Comment by vanderhoop** [comment]
handled within #146
