### ISSUE TITLE
use `Repo.insert_or_update/2` to avoid conditional

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#136]
see auth controller. we're calling `Repo.insert!` when no user found and `Repo.update!` when one *is* found. in its place, we can use `Repo.insert_or_update/2`

__Helpful Link:__
- [`Repo.insert_or_update/2`](https://hexdocs.pm/ecto/Ecto.Repo.html#c:insert_or_update/2)

**Comment by Trevoke** [comment]
Are you at all able to create a path where you do not have to wonder if you
already have this object or not?

**Comment by vanderhoop** [comment]
closing due to completion in commit 090a7c5f053b9350966bf364b8c14b1fe0e100d8
