### ISSUE TITLE
Start New Retro Modal

### ISSUE THREAD

**Issue by imaginista** [stride-nyc/remote_retro#139]
After logging in, instead of showing/asking it this way:

<img width="301" alt="screen shot 2017-05-10 at 11 18 48 am" src="https://cloud.githubusercontent.com/assets/1500663/25909526/734bb40c-357b-11e7-87ef-a2c84b8f9fa1.png">

show/ask it this way:

![appmain overlay](https://cloud.githubusercontent.com/assets/1500663/25909542/81aa0bd4-357b-11e7-97f0-c403a6046f28.png)

**Comment by vanderhoop** [comment]
hey @imaginista, cleaning up the repo issues, and closing this one due to atrophy and the working current design. feel free to reopen if you think we need to revisit this
