### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by brettnbcu** [stride-nyc/remote_retro#140]
@vanderhoop moving conversation from Slack to here.

Dark
![landingpage dark](https://cloud.githubusercontent.com/assets/14983728/25967320/c0f3c452-365b-11e7-9829-69b3b3d61390.png)

Light
![landingpage light](https://cloud.githubusercontent.com/assets/14983728/25967325/c5d36fe0-365b-11e7-9536-c05e6ad478e3.png)

**Comment by vanderhoop** [comment]
hey @brettnbcu, can you add a link to the photograph you're using in these layouts? Thanks!

**Comment by imaginista** [comment]
try this:

https://lh3.googleusercontent.com/87n8IHGHedLoZT0TC5h6VyB9pScsa9uhbePG5BstmqL3K2WKBgX7KIwxU1knDBJDp-34MvxAEl2MoRwrX5-V_MJp5dsGDlb439p6OtssI6AIZQTX_kCbEt6ENy7UZVv9y1VM=w1366-h1024-no

**Comment by vanderhoop** [comment]
closing, as this was implemented
