### ISSUE TITLE
safari, firefox and old versions of chrome: "typing" ellipsis incorrectly positioned

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#142]
__Bug:__

When a user is typing, there should appear an animated ellipsis beneath their photo/video stream, like so (Chrome 57):

![correct](https://cloud.githubusercontent.com/assets/4386645/26057866/6153cbdc-3949-11e7-971c-648a003593c7.gif)

But in Firefox, Safari and older versions of Chrome (I've seen it b0rk on Chrome 49), the ellipsis is way off center:

![b0rked_on_firefox](https://cloud.githubusercontent.com/assets/4386645/26058050/14fa804a-394a-11e7-86ac-05667a1cabee.gif)

**Comment by ianmcnally** [comment]
@vanderhoop do you have a deployed version of the app I could check it in?

**Comment by vanderhoop** [comment]
implemented
