### ISSUE TITLE
style root page

### ISSUE THREAD

**Issue by vanderhoopnbc** [stride-nyc/remote_retro#146]
As a visitor to remote retro,
I want to see a designed retro page that welcomes me to the app,
So that I don't get a bad first impression of the app. 

__Acceptance Criteria:__

- [x] visiting the landing page as an user presents me with the following design
  - [ ] leverages Semantic UI grid
  - __Notes:__ 
    - at this time, there is no need to worry about the responsiveness of this page.
    - when the user *is* authenticated, the conditional logic already in place within [`web/templates/page/index.html.eex`](https://github.com/stride-nyc/remote_retro/blob/master/web/templates/page/index.html.eex) still applies, changing the button text from an invitation to authenticate to an invitation to create a retro.
     - don't ditch the google icon already in place in the template. we want to keep that.

__Assets:__
  - [background photo](https://lh3.googleusercontent.com/87n8IHGHedLoZT0TC5h6VyB9pScsa9uhbePG5BstmqL3K2WKBgX7KIwxU1knDBJDp-34MvxAEl2MoRwrX5-V_MJp5dsGDlb439p6OtssI6AIZQTX_kCbEt6ENy7UZVv9y1VM=w1366-h1024-no)

___

## Design

![image](https://cloud.githubusercontent.com/assets/14280195/26129215/6006a06e-3a5d-11e7-84f6-bd2d0ab77f25.png)

**Comment by vanderhoop** [comment]
closing, implemented!
