### ISSUE TITLE
Remote Retro Component to Redux

### ISSUE THREAD

**Issue by caporta** [stride-nyc/remote_retro#155]
- [x] Connect `remote_retro.jsx` to store
- [x] Leverage channel listeners to successfully dispatch `addUsers`
- [ ] Create reducer + action for dispatching updateUsers (tests)
- [ ] Modify updateUsers to leverage users.token > presences[userToken].user
- [ ] Leverage bindActionCreators from 'react-redux' to batch dispatching

**Comment by ssomnoremac** [comment]
@caporta, the second item is a bit involved, cause you need to add new actions and reducers. Happy to do this myself as I've done it many times before -- or review after you've worked on it. If you want me to do it, can you detail your process for contributing, and what I would need.

**Comment by caporta** [comment]
@ssomnoremac thanks! I just altered it to specifically entail dispatching `addUsers`. @vanderhoop and I will be working on this story tomorrow evening, as well as getting some more Redux stories fleshed out.

For now, I'll write one up re: creating an `idea` reducer & `addIdea` action creator. I'll go ahead and tag you on that with some details about contributing. Thanks!
