### ISSUE TITLE
Create `idea` reducer && `addIdea` action creator

### ISSUE THREAD

**Issue by caporta** [stride-nyc/remote_retro#156]
- [x] Create `idea` reducer (`web/js/reducers/idea.js`)
- [x] [guide for reducer tests](http://redux.js.org/docs/recipes/WritingTests.html#reducers)

- [x] Create `addIdea` action creator (`web/js/actions/idea.js`)
- [x] [guide for action creator tests](http://redux.js.org/docs/recipes/WritingTests.html#action-creators)

**Comment by caporta** [comment]
@ssomnoremac feel free to knock this out and submit a PR.

As far as contributing guidelines go, try to be as idiomatic as possible, use the linter, and test coverage us suuuuper important. Let me know if you have any questions.

**Comment by ssomnoremac** [comment]
@caporta gotta release an app today so I'll most likely not get to it. Also gone this weekend. If you haven't gotten to it by next week I'll do it though.

**Comment by vanderhoop** [comment]
implemented
