### ISSUE TITLE
Augment/Update ShareRetroLink modal to be more explicit/effective

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#159]
Yo @imaginista,
Can you peep the new "Share Retro Link" modal that was recently introduced. It appears when the facilitator first enters the retro, prompting them to share the retro link with others. But the copy I cooked up doesn't seem to be too effective. Can we do something simple, design-wise, to draw the eye and actually have people share the link. thanks!

**Comment by imaginista** [comment]
@vanderhoop just took a look and i think the copy is pretty strong. One thing I did notice is there wansn't a confirmation of successfully copying the link. Check it:

![rr-copy-link](https://user-images.githubusercontent.com/1500663/28733371-c929c10e-73a9-11e7-89c1-c62932838c5d.gif)

Can we add alter the button dialog (or add a small line above) saying "Link copied!" or something similar?

**Comment by vanderhoop** [comment]
closing, as @imaginista's suggestion was implemented and merged in!
![copied](https://user-images.githubusercontent.com/4386645/31389647-e6995a32-ad8e-11e7-8c4a-d542430b3ecd.gif)
