### ISSUE TITLE
Create reducer case and action creator for handling idea updating

### ISSUE THREAD

**Issue by caporta** [stride-nyc/remote_retro#167]
__Acceptance Criteria:__

- [x] Create case for `UPDATE_IDEA` in `idea` reducer (`web/js/reducers/idea.js`)
    - given an id and a key-value object of attributes to update, this case should update the idea with matching id such that it uses the new attributes
    - current idea updating implementation can be seen [in this helper](https://github.com/stride-nyc/remote_retro/blob/master/web/static/js/components/remote_retro.jsx#L11-L15), which is leveraged within the callbacks for, `retroChannel.on("enable_edit_state")`, `retroChannel.on("disable_edit_state")`, `retroChannel.on("idea_live_edit")`, and `retroChannel.on("idea_edited")`
- [x] Create corresponding `updateIdea` action creator (`web/js/actions/idea.js`)

__Helpful Links:__
- [ ] [guide for reducer tests](http://redux.js.org/docs/recipes/WritingTests.html#reducers)
- [ ] [guide for action creator tests](http://redux.js.org/docs/recipes/WritingTests.html#action-creators)

**Comment by vanderhoop** [comment]
implemented
