### ISSUE TITLE
persist user_id on `idea` records

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#173]
As a developer,
I would like to uniquely associate an idea with its author,
So that I can associate an idea with additional user metadata (as opposed to only the given name of the author).

__By Way Of Explanation:__ when we initially implemented the story that surfaced an idea's author in the UI, we weren't persisting users in the database. Therefore, to complete the story, we just passed along and persisted the author's given name (provided by google oauth) on the `ideas` table. Now that we have a proper `users` table, we want to ensure we're properly associating ideas to the user who submitted the idea. 

__Acceptance Criteria:__

- [x] there is a new column, `user_id`, on the `ideas` table
- [x] when a user submits a new idea, their `id` is persisted in the `user_id` column

__Helpful Links:__

- [Ecto.Migration docs](https://hexdocs.pm/ecto/Ecto.Migration.html)

**Comment by qlaire** [comment]
@vanderhoop should we get rid of the author field now that we have the user_id?
