### ISSUE TITLE
close retros upon entering the 'action-item-distribution' phase

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#182]
As a facilitator who has just triggered the distribution of action items,
I would like all connected clients to have their UI enter a 'closed' state,
To communicate the closure of the retro.

__By Way Of Explanation:__ When we initially implemented the action item distribution email, the thinking was that we didn't want to disable the retro UI, so that that the emails could be triggered again, should it fail the first time). This was has proven--to this point--to be overly cautious. The intent is for the distribution of action items to represent a 'closing' of the retro.

__Acceptance Criteria:__

- [x] upon clicking the "Distribute Action Items" button, a confirmation modal appears, reading, "Are you sure you want to distribute this retrospective's action items? This will close the retro."
  - Helpful direction: peep the [`StageProgressionConfigurations`'s `confirmationMessage` attribute](https://github.com/stride-nyc/remote_retro/blob/master/web/static/js/configs/stage_progression_configs.js#L11)
- [x] change current alert text ("The facilitator has distributed this retro's action items. You will receive an email breakdown shortly.") to "The facilitator has closed this retrospective. You will an email containing the retrospective's action items shortly."
- [x] the `IdeaGenerationComponent` lower third is removed from the page so that no further action items can be submitted
- [x] the `IdeaControls` are removed from the page so the record of the retro can no longer manipulated/rewritten
- [x] _a nice to have:_ renaming the 'action-item-distribution' stage to 'closed' across the codebase, as it is a more accurate representation
 😄

**Comment by vanderhoop** [comment]
blocked, as acceptance criteria is incomplete

**Comment by tnewell5** [comment]
hey @vanderhoop did I screw up the last commit? Trying to figure out why you reverted it. Thanks!

**Comment by vanderhoop** [comment]
needs a test! for the conditional render of the idea controls!
