### ISSUE TITLE
allow facilitator to pass facilitatorship to other user

### ISSUE THREAD

**Issue by caporta** [stride-nyc/remote_retro#190]
As a facilitator who needs to leave the retrospective before it's over,
I would like the ability to pass the facilitatorship to a specific user,
So that the retro can advance without me.

__Acceptance Criteria:__

- [x] the facilitator--and only the facilitator--sees "magic" icon (looks like a wand) in upper right hand corner of non-facilitator's photo area
  - upon hovering over the magic icon, we see a title that reads "Transfer facilitatorship"
  - upon clicking over the magic icon, a native javascript confirm window pops up reading "Are you sure you want to transfer the facilitatorship to [NEW_FACILITATOR_TARGETS_FULL_NAME]"
- [x] upon receiving the facilitatorship, the new facilitator is alerted that they are now the facilitator, and responsible for advancing the retrospective.
- [x] upon receiving the facilitatorship, the new facilitator's UI updates with facilitation components

**Comment by caporta** [comment]
yo @imaginista, if we wanted to pass the facilitatorship from facilitator to someone else (explicitly), could you come up with a couple directions/ideas for UI components for doing so.

ps. this is travis speaking via Chris's GitHub account

**Comment by imaginista** [comment]
I'm thinking enable that control directly on the facilitator avatar. Complete action in 3 clicks:

1) pull up menu of participants the current facilitator can pass the role to
2) select the participant
3) apply (ahem, bestow) new role

Screen flow attached (quick and dirty to show experience - disregard "design" fidelity)

![rr-fac-pass-1](https://user-images.githubusercontent.com/1500663/28231809-69080522-68bb-11e7-9803-05129f028922.png)
![rr-fac-pass-2](https://user-images.githubusercontent.com/1500663/28231811-690e98a6-68bb-11e7-97fb-cbe88f7080a3.png)
![rr-fac-pass-3](https://user-images.githubusercontent.com/1500663/28231810-690c5104-68bb-11e7-9ff7-79db61872183.png)

**Comment by imaginista** [comment]
SVG for facilitator control here:
[avatar-facilitator-control.svg.zip](https://github.com/stride-nyc/remote_retro/files/1149733/avatar-facilitator-control.svg.zip)

**Comment by imaginista** [comment]
@caporta @vanderhoop (see above)

**Comment by vanderhoop** [comment]
removing blocked label, as there is nothing holding this story back.

**Comment by vanderhoop** [comment]
moving back to backlog, as there are a lot of ui concerns here, and want to break up the story into smaller pieces.

**Comment by vanderhoop** [comment]
Want icon for transferring facilitatorship: 
![image](https://user-images.githubusercontent.com/4386645/37563422-d8c5d06e-2a45-11e8-88c4-c4d48279f635.png)

**Comment by vanderhoop** [comment]
@caporta thank you for creating this, and thank you @edem-ca for taking it on. this goes live momentarily ❤️
