### ISSUE TITLE
Inform new facilitator of status & responsibility

### ISSUE THREAD

**Issue by caporta** [stride-nyc/remote_retro#191]
As a user who has just become a facilitator,
I would like be informed of my status & responsibilities,
so that I know what is expected of me.

__By Way Of Explanation:__
At the moment that the facilitator role passes from one user to another, responsibilities are implicitly granted, with no announcement of any kind. It would be better to explicitly lay out the responsibilities of the new facilitator.

__Acceptance Criteria:__

- [x] Recipient of facilitatorship should be alerted to their new status & responsibility via [the existing `Alert` interface](https://github.com/stride-nyc/remote_retro/blob/master/web/static/js/components/alert.jsx)
  - Alert's `headerText` reads: "Facilitation Transfer!"
  - Alert's body reads: "With {previousFacilitatorName}'s departure, you have assumed the role of facilitator. You'll be responsible for advancing the retro!"
- [x] other users are alerted to no such thing

**Comment by caporta** [comment]
yo @imaginista, travis and I were talking about non-experienced facilitators (or just new users to the tool) being thrust into the facilitator role. How would they know what do do? We don't want to explain every little thing, but we were thinking it might make sense to at least let them know they'll be counted on to trigger stage progressions, edit vague ideas, et cetera. Is that a no-no from a UI perspective? How do we do that in such a way that it doesn't suck?

**Comment by imaginista** [comment]
@caporta @vanderhoop 

Providing support and helpful information is critical to a good experience, but I don't think we should design some novel experience that instructs a user during an in-flight retro. My gut tells me we should design some cool little on-boarding one pager that someone can read 20 minutes before a RR and get the gist of the controls. 

Remember, Retrospectives are expensive. RR should be a tool that deserves the respect of the facilitator at hand to understand and feel confident before using. So, ideally, there are no in-flight facilitator transfers and if there are, the new facilitator could reference a help.remoteretro.com page for drop dead simple instructions on using it. 

IOW/TL;DR - I think we should design a help.remoteretro.com page.

**Comment by imaginista** [comment]
@caporta @vanderhoop 

Riffing off above: im questioning the value of a facilitator-transfer ability. is this an ultra edge case? If someone has to bow out of leading a retro and the rest of the group wants to carry on, couldn't one of the participants just say "hey guys, I'm going to reschedule another retro to start in X minutes. Stand by for a new link"?

**Comment by caporta** [comment]
@imaginista @vanderhoop  I think this feature has value primarily in two cases:

1) Facilitator has to leave mid-retro, when ideas have largely been generated already, so the cost of starting a fresh retro is too high
2) Facilitator accidentally gets logged out for one of many reasons.

Since the facilitatorship operates on the user list as a queue (first person in, first person out), the baton is automatically passed to the person who logged into the retro second (which could be anyone, including a client stakeholder), and the original facilitator is placed at the _end of the queue_ when logging back in. I think this is where reassignment functionality in particular has a strong value prop.

These may be edge cases, but I can think of scenarios where their UX costs are particularly high.

Thoughts?

**Comment by imaginista** [comment]
@caporta That makes sense. Two thoughts:

1) Assuming story #190 addresses transfer functionality from a design standpoint (by "design" I mean functional - not aesthetic) can we say that the iconography assigned to the new facilitator avatar solves the "status" issue addressed in this story?  

2) I think the "Responsibility" aspect of this story deserves more in-person discussion. I'm not sure how valuable it is to design an experience that supports educating a user on RR usage during an in-progress retro. Certainly we could re-purpose existing design elements like the floating tooltip used for idea entry:

<img width="626" alt="screen shot 2017-07-28 at 4 24 39 pm" src="https://user-images.githubusercontent.com/1500663/28734986-5470aa00-73b1-11e7-898f-936143da2d98.png">

...but introducing new elements and/or an on-boarding walkthrough is convo worthy.

(cc @vanderhoop )

**Comment by vanderhoop** [comment]
hey @caporta and @imaginista, prioritizing this as the first step in a series of facilitation transfer stories, as it has now bitten 3 teams that I know of. re-wrote the criteria, though the copy.

**Comment by vanderhoop** [comment]
adding a 'blocked' label until #190 is implemented
