### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by samdec11** [stride-nyc/remote_retro#208]
As a prospective contributor,
I would like to see contribution guidelines,
So that I know the processes I should follow when I want to contribute to Remote Retro.

__Acceptance Criteria:__

- [x] A CONTRIBUTING file exists with guidelines
- [x] The README has been updated to point to this new file.

__Helpful Links:__

- [Github's guide to writing the contributing guidelines](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines)

**Comment by qlaire** [comment]
@vanderhoop we're wondering if we should add a requirement to sign a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement). I know that Stride might want to close source/make money off of this in the future.
