### ISSUE TITLE
persist users' votes 

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#235]
As a retro participant,
I would like to reconnect to a retro I've left and see the correct vote count for all ideas on the board,
So that I can determine how to spend my votes using up-to-date information.

__By Way Of Explanation:__ in the interest of incrementally developing the voting feature, story #232 doesn't involve any sort of persistence. This story ensures that, upon reloading a retro, we see the correct vote counts for the ideas on the board.

__Acceptance Criteria:__
- [x] upon clicking the "Vote" button implemented in #232
  - [x] the vote_count is increased on the idea table
  - [x] the vote_count is increased on the participation table
  - [x] wrap the two SQL queries for doing the above in a transaction

- [x] upon reloading a retro with persisted votes, we see their vote counts on the board

__Helpful Links:__

- [`Ecto.Migration` docs](https://hexdocs.pm/ecto/Ecto.Migration.html)
- [`Ecto.Schema` docs](https://hexdocs.pm/phoenix/ecto.html#the-schema)

**Comment by qlaire** [comment]
@vanderhoop just wondering why it's better to have a separate votes table instead of incrementing and decrementing a vote_count field on the user and idea. Lemme know!

**Comment by vanderhoop** [comment]
hey @qlaire, i'm not against that approach. my original thinking was that votes wouldn't be anonymous, but based on the discussion in the #remote-retro channel last week, i'm all for users and vote

a couple things to keep in mind with this approach:
1. we'll want to increment the `vote_count` on the `participations` table rather than the `users` table, as a `participation` links a given user to the retro, and the vote limiting is scoped to a particular retro 
1. we don't want to increment an `idea`'s vote_count if the incrementing of the `participation`'s vote count somehow fails (and vice versa), so you'll want to wrap the two SQL queries in a transaction.
