### ISSUE TITLE
Assignees and Due dates for action items

### ISSUE THREAD

**Issue by qlaire** [stride-nyc/remote_retro#241]
As a facilitator,
I would like the ability to attach assignees and due dates to action items,
So that who is responsible and by when is more clear.

__Acceptance Criteria:__

- [ ] Due date for action item persists in DB
- [ ] Assignees persist in DB (Many to Many Relationship)
- [ ] Date picker appears next to action items
- [ ] Assignee icon appears next to action items. Clicking the icon drops causes a field to type assignee name into to appear. Field only allows names of current retrospective participants.

**Comment by vanderhoop** [comment]
hey @qlaire, love that you made this ussue. One thought I have is that we could break these out into separate stories ("assign due-date to action item" and "assign assignee to action item") to allow for a more iterative (and potentially parallelizable) workstream. thoughts?

**Comment by vanderhoop** [comment]
also, i think we'll need to update the action items email that gets sent out, so there is a record-slash-reminder of these assignments.

**Comment by qlaire** [comment]
@vanderhoop good idea, I'll break this issue up

**Comment by qlaire** [comment]
I've broken this issue up into #248 #247 #249
