### ISSUE TITLE
Allow retro configuration option to show author attribution next to ideas

### ISSUE THREAD

**Issue by qlaire** [stride-nyc/remote_retro#242]
As a facilitator,
I would like to be able to configure the retro such that ideas are attributed to their author,
So that I can identify the author and ask them for clarification where necessary.

__Acceptance Criteria:__

- [ ] TBD

Just an implementation detail, but trying to decide if the option should be added to the ShareRetroLinkModal or to the PrimeDirectiveStage modal. Or elsewhere?

**Comment by vanderhoop** [comment]
we changed the default behavior to *not* render the users name in 606b2f1edaf6bbf245573ec90a8f17c0f6f4335b, so @qlaire going to change the name of this to be "allow option to show names next to ideas", as we may way to allow folks to configure that to their liking down the road.

**Comment by vanderhoop** [comment]
adding blocked label on acceptance criteria is hammered out

**Comment by vanderhoop** [comment]
closing this for now, as this story was based on an assumption that I made about folks wanting this. folks seem comfortable with the switch we made to have anonymous submissions
