### ISSUE TITLE
Disable voting buttons once in Action-Items stage

### ISSUE THREAD

**Issue by tnewell5** [stride-nyc/remote_retro#245]
As a facilitator,
I would like the voting buttons to be disabled once in Action-Items stage,
So that participants are no longer able to submit votes after the voting stage is closed.

__Acceptance Criteria:__

- [ ] vote buttons are disabled so that when a participant clicks on 'vote', the number of votes remains the same
- [ ] vote button looks disabled (maybe grey or a lighter color)

**Comment by vanderhoop** [comment]
@qlaire @tnewell5 maybe you already thought of this, but wanted to call it out: the voting button should not be visible once the retro has been closed, following the logic you're implementing in #182 (currently in progress)
