### ISSUE TITLE
Assignees for Action Items

### ISSUE THREAD

**Issue by qlaire** [stride-nyc/remote_retro#248]
As a participant,
I want to be able to assign action items to a particular user
So that that each action item has an accountable party.

__By Way Of Explanation:__ accountability is crucial for action items. if no one is named responsible for a given action item, the likelihood that it gets finished goes way down. To this point, the only way to "assign" an action item was to add an assignees name to the "body" of an idea. 

__Acceptance Criteria:__

- in the "action-items" stage, the lower third looks much like the `IdeaGenerationLowerThird`, but: 
  - [ ] "Category:" is replaced with "Assignee:"
  - [ ] In place of the category select dropdown, there is a different select dropdown populated with the full names of the users current present in the retro.
  - [ ] the form's "Submit" button is disabled until an assignee is selected
  - [ ] Once an action-item is submitted, any action item listed on the board has its assignee listed in parentheses after the idea's "body", but before the optional "(edited)" indicator
    - Example action item: `Take out the trash (Travis Bibimbap)`
      - when the idea's been edited `Take out the trash (Travis Bibimbap) (edited)`
  - [ ] upon reloading an idea board that has action items, its assignee is still listed either before or after (basically, the assignee needs to be persisted)

__Helpful Links:__

- [Action Item WikiPedia Page](https://en.wikipedia.org/wiki/Action_item)

**Comment by williamcodes** [comment]
+1 from JOOR CTO

**Comment by vanderhoop** [comment]
looks like @damonblack pushed up a branch for this: https://github.com/stride-nyc/remote_retro/tree/add_assignments
