### ISSUE TITLE
Update Action Item Email With Assignees

### ISSUE THREAD

**Issue by qlaire** [stride-nyc/remote_retro#249]
As a participant of a completed retro,
I would like the action item breakdown email that I receive to include the assignee,
So that I have a record of who is responsible for what.

__Acceptance Criteria:__

- [ ] assignee is included in the action item email next to the action item

**Comment by vanderhoop** [comment]
adding blocked label, as this story depends on the completion of #248

**Comment by vanderhoop** [comment]
no longer blocked!

**Comment by vanderhoop** [comment]
closing, as this was implemented. thanks @tnewell5!
