### ISSUE TITLE
Lower volume of sign in/sign out sound

### ISSUE THREAD

**Issue by qlaire** [stride-nyc/remote_retro#254]
As a facilitator/non-facilitator,
I would like the sign in/sign out sound to be quieter,
So that I am not annoyed, but still notified.

__By Way Of Explanation:__ during Orchard's use of Remote Retro, many people complained about the current sound being annoying.

__Acceptance Criteria:__

- [x] sign in/sign out sound is quieter, but still audible

**Comment by vanderhoop** [comment]
implemented. less abrasive!
