### ISSUE TITLE
Enable editing for non-facilitators

### ISSUE THREAD

**Issue by qlaire** [stride-nyc/remote_retro#255]
As a non-facilitator,
I would like to be able to edit my ideas,
So that I can correct typos or other mistakes.

__By Way Of Explanation:__ Currently only facilitators are able to edit ideas, and they can edit any and all ideas. This story represents a follow-up to that story, but scopes a non-facilitator's edits to the ideas that they've submitted.

__Acceptance Criteria:__

- [ ] When the user is a non-facilitator, the edit icon is exposed on any idea belonging to them.
- [ ] upon clicking the edit icon, the edit form appears in place of the line item.
  - __Note:__ there is already an `IdeaEditForm` component that should be available for reuse.
- [ ] upon clicking "Save", the edit form disappears and the idea appears edited across all connected clients
- [ ] live edits are _not_ exposed to other users, i.e. other users should not see that the user is editing their idea.
  - __Note:__ this differs from the live edits of the facilitator, which are exposed in real time so that participants can assist the facilitator in clarifying a vaguely worded idea.

**Comment by qlaire** [comment]
We can add editing onto idea controls, but should it always be visible, or only for 5 seconds similar to the delete button?

**Comment by vanderhoop** [comment]
my thinking is that it should be for five seconds, because we don't want anyone re-writing history after folks have taken the idea in, and if a user makes a typo, they generally spot it within seconds of it going on the board.

**Comment by vanderhoop** [comment]
created a spike story, #258, to discover the scope of this feature so we can prioritize appropriately

**Comment by vanderhoop** [comment]
closing, as this was completed almost a month ago!
