### ISSUE TITLE
Fix github new issue template

### ISSUE THREAD

**Issue by Trevoke** [stride-nyc/remote_retro#262]
As a contributor,
I would like the new issue template to better show that the third line is supposed to demonstrate the value delivered, not just what people are trying to accomplish,
So that we can develop better empathy towards the given role and better do prioritization based on value.

As a _role_,
I want _something_
So that _this value is delivered to me_

**Comment by vanderhoop** [comment]
great insight, @Trevoke. Just updated the template!
