### ISSUE TITLE
Participants should not be allowed to add ideas during voting stage

### ISSUE THREAD

**Issue by qlaire** [stride-nyc/remote_retro#264]
As a facilitator,
I want to prevent participants from submitting additional ideas during the voting stage,
So that I can keep idea generation and voting stages separate.

__By Way Of Explanation:__ Currently users can add additional ideas during voting. Should we avoid this by disabling the submit button or just removing the IdeaGenerationLowerThird from view completely?

__Acceptance Criteria:__

- [ ] TBD

**Comment by vanderhoop** [comment]
hey @qlaire, good catch. I'll let you and @ams340 make the call on the prioritization of this one, as one of the acceptance criteria in #236 calls for the replacement of the IdeaSubmissionForm with the a "X Votes Left" indicator, which maybe suggests that I should have broken that out into it's own story, which I'll do now.

**Comment by vanderhoop** [comment]
@qlaire @ams340 woops! let's catchup before I create a new issue, as I'm not sure if you would have taken the criteria in #236 (mentioned above) on first or not. Don't want to create a story for something you might already have in flight. lemmeknow!

**Comment by vanderhoop** [comment]
@qlaire @ams340 adding blocked label until i hear back from ya. feel free to remove, using your best judgement given your status on #236

**Comment by vanderhoop** [comment]
closed in favor of #269
