### ISSUE TITLE
Display number of votes left for participant

### ISSUE THREAD

**Issue by qlaire** [stride-nyc/remote_retro#269]
As a participant,
I would like to see how many votes I have left,
So that I can better plan how I would like to spend my votes.

__Acceptance Criteria:__

- [x] the idea submission form (housed in the lower third) is replaced with displays "X Votes Left", where X is the number of votes the user has left, starting from 5.
- [x] as a user's votes are persisted, X decrements appropriately.
- [x] to avoid the "X votes left" line shifting position as the X value changes, have X on one line, and "Votes left" centered below it. 

__Example:__
```
                                            5
                                       Votes Left
```

**Comment by vanderhoop** [comment]
closing as
