### ISSUE TITLE
Feature request: Track what I've voted on

### ISSUE THREAD

**Issue by samdec11** [stride-nyc/remote_retro#274]
As a participant,
I want a visual indication of which ideas I've voted on
So that I am not confused about which ones have already gotten my votes.

__By Way Of Explanation:__ Because I have no visual indication of what items I've voted on, I have to remember which ones I've clicked on already, otherwise I waste a vote clicking on an item that already has my vote.

__Acceptance Criteria:__

- [ ] There is some visual cue to differentiate what I've voted on from what I haven't.

@imaginista, will probably need your input here.

**Comment by vanderhoop** [comment]
i think we'll get this for free if we implement "Blind Voting" (#277), as then the only ideas where the votes will increment will be those of the present user

**Comment by vanderhoop** [comment]
hey @samdec11, we recently implemented Blind Voting. Let me know if that helped the tracking, or if you want to leave this open for a more full-fledged feature discussion

**Comment by samdec11** [comment]
@vanderhoop Blind voting makes this request unnecessary, but I know there have been requests to make blind voting optional. If that is ever implemented, there will still be a need for individuals to be able to tell what they've voted on.

**Comment by vanderhoop** [comment]
@samdec11 Thanks for the quick response. I'm going to leave this open for the time being.

**Comment by vanderhoop** [comment]
closing, as users can now track their votes and detract as necessary.
