### ISSUE TITLE
Double digits on the votes expands its container

### ISSUE THREAD

**Issue by ddipanfilo** [stride-nyc/remote_retro#284]
As a participant, I want the number of votes to be aligned, particularly when the number of votes gets into double digits.  In other words, when votes get into double digits, the box containing the double digit votes expands larger than single digit votes.

This is a minor UI feature that will make RR look more polished.

**Comment by vanderhoop** [comment]
hey @ddipanfilo, closing this one as a wontfix, as this alignment issue will go away in the grouping stage, as the vote interfaces won't be within stacked ideas, but rather be group-specific. still, i appreciate you creating the issue
