### ISSUE TITLE
Only close "Share Retro Link Modal" via close button

### ISSUE THREAD

**Issue by phlco** [stride-nyc/remote_retro#290]
As a first-time faciliator,
I do not want to be able to click outside of the Share Retro modal and have it close
So that I don't accidentally miss out on important information.

__Acceptance Criteria:__

- [ ] clicking outside the share retro link modal should not close it

**Comment by vanderhoop** [comment]
addressed in b3782731ce08840eedda508304d9028125f4afaf!
