### ISSUE TITLE
Icons move when user is typing

### ISSUE THREAD

**Issue by ddipanfilo** [stride-nyc/remote_retro#291]
As a participant, I want the user icons to stay in one place.

Currently, when there are more than about 5 people on RemoteRetro on Google Chrome 60 and the facilitator is typing, the icons with people's names and faces flip rapidly back and forth.  This happens for facilitator and participants alike.

![dancing_in_the_screen_3](https://user-images.githubusercontent.com/16329314/31153837-4db0375e-a871-11e7-8a35-cbb683691612.gif)

**Comment by vanderhoop** [comment]
Several interesting behaviors I saw on my machine (gif below), that could prove fruitful when investigating this bug.

1. the `is_typing` attribution is bizarre. it’s supposed to be scoped to a specific presence, but it switches between two separate presences of the same user
1. the facilitator isn't being listed as the first user, though they should be, as the user list is sorted by arrival timestamp, ascending, and the facilitatorship always goes to the user who arrived earliest. 

![bug](https://user-images.githubusercontent.com/4386645/31153955-2978acbe-a861-11e7-9230-84865fccf965.gif)

**Comment by vanderhoop** [comment]
closing, as this was fixed!
