### ISSUE TITLE
allow facilitator to see who has completed voting

### ISSUE THREAD

**Issue by Mnunez903** [stride-nyc/remote_retro#294]
As a Facilitator,
I want to know when a user has finished submitting their votes,
So that I don't move on to the next part of the retro before participants have had a change to  submit all of their votes.

__Acceptance Criteria:__ 

- [ ] When a user has used all of their votes, the facilitator should see a [Semantic UI "floating" label](https://semantic-ui.com/elements/label.html#floating) reading "Votes Submitted" just over the user's image.
  - we can iterate on the text displayed (as well as icons) going foward, as I suspect this may be too verbose. 
- [ ] Non-facilitators can never see whether a user has used all of their votes
  - this helps to preserve the anonymity of votes, to what extent it's possible

**Comment by Trevoke** [comment]
Question: should participants be able to abstain from voting, if they don't want to use all their dots?

I don't know if we care about showing individuals not being done voting -- because if we do that, then voting becomes slightly less anonymous.

**Comment by Mnunez903** [comment]
Yea, that was a concern I had about it. I feel that people should be able to not vote. When I had a retro, I was unsure if people were just voting or waiting for the next part of the retro.

**Comment by Trevoke** [comment]
On the one hand, I think "everyone in the room should vote", and on the
other hand, I think that if someone wants to not vote, then there are
deeper dysfunctions in the team and forcing people to vote won't help.

**Comment by vanderhoop** [comment]
In ideal circumstances, everybody on a team would submit some/all of their votes, but I can see circumstances where they might want to abstain. For example, I can see a participant on their first day (or, god forbid, a c-level sitting in on a team's retro) not wanting to sway the discussion.

**Comment by vanderhoop** [comment]
Hey @Mnunez903 and @Trevoke, updated the acceptance criteria to be as minimalist as possible while still protecting the anonymity of votes.

**Comment by Trevoke** [comment]
*nod* I like it.

**Comment by vanderhoop** [comment]
hey @Trevoke and @samdec11, just pushed this feature! lemmeknow if it works out for ya!

**Comment by Trevoke** [comment]
Awesome, thanks!
