### ISSUE TITLE
Implement Retro Lobby

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#298]
As a retro participant,
I want the first "stage" I experience to let me know what to expect in the retro,
So that I don't just enter the prime directive stage with no clear path forward.

__By Way Of Explanation:__ at the moment, the first "stage" of a retro is the prime directive stage. This has produced confusion for facilitators and non-facilitators alike, as there is no clear user action they can take. This story is meant to inform users so that they're not in the dark, and will allow us to create enhancements to the lobby (like a scratchpad that users can write down events/ideas on while waiting).

__Acceptance Criteria:__

- [x] retros begin with the lobby stage, rather than the prime directive stage
- [x] the lobby stage's layout is similar to that of the Prime Directive, consisting of a centered header, some left-justified body text, and the stage progression button.
  - Header text reads "Retro Lobby"
  - Body text reads:
    - [x] if facilitator: "Hi {facilitatorName}. Welcome to RemoteRetro! Once your party has arrived, it will be your responsibility to start the retro, which you can do by clicking the button below."
    - [x] if non-facilitator participant: "Hi {nonFacilitatorParticipantName}. Welcome to RemoteRetro! Once your party has arrived, your facilitator, {facilitatorName}, will begin the retro. Until then, hold tight!"
- [x] lobby's stageConfig ([see stageConfigs](https://github.com/stride-nyc/remote_retro/blob/master/web/static/js/configs/stage_configs.jsx)) changes to:
```
{
  confirmationMessage: "Has your entire party arrived?",
  nextStage: PRIME_DIRECTIVE,
  progressionButton: {
    copy: "Begin Retro",
    iconClass: "arrow right",
  },
}
```
- [x] the Prime Directive stage gets an `alert` ([again, see stageConfigs](https://github.com/stride-nyc/remote_retro/blob/master/web/static/js/configs/stage_configs.jsx)), where the alert's header text reads "Stage Change: The Prime Directive!", and the body of the alert reads "The Prime Directive is used to frame the retrospective, such that the time spent is as constructive as possible. Read it to yourself, and try to keep it in mind as the retro moves forward."

__Helpful Links:__

- [RemoteRetro's Stage Configs file](https://github.com/stride-nyc/remote_retro/blob/master/web/static/js/configs/stage_configs.jsx)

**Comment by vanderhoop** [comment]
blocked until criteria is established

**Comment by vanderhoop** [comment]
closing due to atrophy. at the moment

**Comment by samdec11** [comment]
@vanderhoop What should the `confirmationMessage` for the prime-directive stage be changed to?

**Comment by vanderhoop** [comment]
@samdec11 Up to you!
