### ISSUE TITLE
Feature Discussion: intercept leave events when user is facilitator 

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#302]
Hey @ianmcnally and @caporta!

Both of you has had the issue of either a) mistakenly leaving/refreshing a retro that you're facilitating, and having the facilitatorship passed to another user as a result. I'm curious what you think of leveraging the `window.onbeforeunload` event when the "unload"ing user is the facilitator, and firing of a `confirm` so that they know the results of their leaving.

Is that an awful user experience? Let me know your thoughts! Could be a low-cost way of avoiding unwanted facilitator-shifts.

Note: we'd have to do some sort of conditional check for whether or not there are multiple folks in the room. i.e. we wouldn't want people who are just checking out the app (and therefore alone) to get notified.

**Comment by ianmcnally** [comment]
There are some warnings here about prompting on the event: https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload

**Comment by vanderhoop** [comment]
Rather than using a `window.{prompt,confirm}`, we could use the custom confirmations we've built for stage progression. I'd want us to spike on it to see how it works in different browsers before greenlighting and prioritizing a story.

**Comment by vanderhoop** [comment]
@ianmcnally @caporta Closing this, as the business rule of longest-tenured-user-is-facilitator has been destroyed!
