### ISSUE TITLE
Submit PR adding RemoteRetro to the awesome_elixir Applications list

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#310]
As a product owner,
I want RR listed in [awesome_elixir](https://github.com/h4cc/awesome-elixir#applications)
So that elixirists have an additional way of finding the application.

__By Way Of Explanation:__ we recently got added to `awesome-phoenix`, and it's resulted in a number of people finding their way to our repo. And the best SEO metric is how many sites *link* to your site. So let's make sure we're getting ourselves linked to on awesome-elixir.

__Acceptance Criteria:__

- [x] PR is submitted to `awesome_elixir` in the *Applications* section, linking to our repo, and the live app, as seen in the [awesome-phoenix repo](https://github.com/droptheplot/awesome-phoenix#awesome-phoenix)

**Comment by tnewell5** [comment]
![image](https://user-images.githubusercontent.com/8727588/33402148-a1a75c5e-d529-11e7-9b8c-7f33e9bbbb61.png)

**Comment by tnewell5** [comment]
PR has been accepted - Remote Retro is now listed on awesome_elixir
