### ISSUE TITLE
Remind Users with Assigned Action Items of Upcoming Due Date

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#311]
As a user with an assigned action item that has upcoming due date,
I want to be reminded of that upcoming due date,
So that I follow-through on the action item.

__By Way Of Explanation:__ action items are the most important thing to come out of a retro, but often users don't follow through due to forgetfulness. This story is meant to head this problem off by sending the responsible party a reminder shortly before the action item's due date.

__Acceptance Criteria:__

- [ ] Every night, a scheduled job fires off individualized emails to users who have action items that are due 3 days from the job's runtime, reminding the user to complete the action item.

```
Hi Travis!

Just a reminder that the following action items are due on Thursday, November 23. That's three days from now!
  
  - schedule job to ping sales with new user leads

Looking forward,
The RemoteRetro Team
```

__Helpful Links:__

- [Heroku Scheduler](https://elements.heroku.com/addons/scheduler)
- [Bamboo (email library)](https://github.com/thoughtbot/bamboo)
  - __Note:__ the bamboo docs assume you're sending emails in the context of a Phoenix app. Because this job is scheduled, it makes more sense to house it in a mix task that Heroku scheduler can invoke. Hence, you may run into issues with making sure the `bamboo` application is started by the elixir supervisor.

**Comment by joebew42** [comment]
Hi @vanderhoop , I would like to help you with that project and I find that this is a feature I can tackle.

Let me know if you have a gitter chatroom or slack channel you use to chat about this project. I am used to go live on [Twitch.tv](http://twitch.tv/joebew42) where I stream about contributing to opensource projects by keeping an eye to the practices like Clean Code, TDD and Refactoring, and yes, that project is the one I am trying to contribute in right now :smile: 

In this period I decided to learn more about Elixir, so I am looking for Elixir projects to contribute in.

Thank you so much!

**Comment by vanderhoop** [comment]
hey @joebew42! Apologies for the delayed response on this issue! We're actually closing this particular ticket, as the need has been lessened. However, I'll definitely keep you in mind for Elixir tickets/issues when they arise. Should I just create an issue on your twitch repo as they come up? Lemmeknow!

**Comment by joebew42** [comment]
Hi @vanderhoop ,

thank you for your answer. Absolutely, as soon as you have some issue you think I could hack on, you can open an Issue on my Twitch Repo :+1:
