### ISSUE TITLE
Mobile Audit

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#312]
As a product owner,
I want to a list of lost-cost improvements we can make to the mobile experience, 
So that I can prioritize those fixes by value.

__By Way Of Explanation:__ Semantic UI's grid exposes some really nice functionality that allows you to specify device visibility, so if you want to hide elements in mobile, or, say, only show an element in mobile screen sizes, you can. We should take advantage of this functionality to improve our mobile experience in a low-cost way.

__Deliverables:__

- [ ] GitHub issues with application screengrabs identifying cumbersome elements that can be removed or swapped with a more mobile-friendly element

__Helpful Links:__
- [SemanticUI Grid Definitions](https://semantic-ui.com/collections/grid.html#/definition)
  - __Note:__ I can't deeplink to the section on Device Visibility, but a simple search will take you there.

**Comment by vanderhoop** [comment]
One thing to note in the proposed layout for idea submission above is that the 'category' state is currently localized in the idea submission form. we'd have to lift that state up (likely into the redux store) for ideas to be submitted to the currently viewed category. 

example: Bobby taps the 'Sad' tab, and all ideas he submits while in that tab would be to the 'Sad' column. 

☝️ is that dumb? the other idea is that, we _leave_ the category select input as is, _regardless_ of whether the user is currently viewing that tab. So a user could have selected the 'Sad' tab, but submit to a totally separate category, per the select input...

**Comment by vanderhoop** [comment]
For reference, here's the _current_ mobile experience: 

![image](https://user-images.githubusercontent.com/4386645/44785019-664c2100-ab87-11e8-8cb4-3ce64b334c23.png)

Barf!

**Comment by ddipanfilo** [comment]
I like it. this would be very usable. consider moving the happy, sad, confused to the bottom and removing the people who are in the room completely.  I'm going to try to find time to work on this on Labor Day

**Comment by edgenard** [comment]
I think this is a big improvement. If it’s similarly low-cost I would remove the avatars at the bottom. It becomes useless on mobile with more than 5 or 6 people. And we regularly have more than 10 at 2U

**Comment by NathanRiemer** [comment]
Ran this by a couple product people at 2U. They like the tabs, but aren't sure about having to be on a given tab to submit an idea for it -- they'd rather have that selector be separate.
Agree that avatars at the bottom is unnecessary. It's really only the facilitator who needs to see those, to know when everyone has voted or I guess to see that people are still typing. Might consider having the option to hide participants even on the non-mobile version.

**Comment by ianmcnally** [comment]
yes to everything here 👏

**Comment by vanderhoop** [comment]
Hot! just cooked up the first of several tickets for this: https://github.com/stride-nyc/remote_retro/issues/485

**Comment by ianmcnally** [comment]
@ddipanfilo where're those labor day commits bruh?

**Comment by vanderhoop** [comment]
closing this, as #485 was the output and has been groomed! thanks all!
