### ISSUE TITLE
High-Level Landing Page Design Options in Wireframes

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#313]
As a product owner,
I want to see different options for landing pages designs,
So that we can settle on one or two to implement-slash-a/b-test .

__By Way Of Explanation:__ the current landing page is fairly barebones, and forces the user to create a retrospective to even see what features are available. This is offputting to first time visitors. We want to provide a high-level breakdown of what the app offers to increase conversion.

__Deliverables:__

- [ ] Two or three wireframes that provide a breakdown of the key aspects of RR

**Comment by imaginista** [comment]
Assigning this to @nonlinear. He's working on it with Zach.

**Comment by vanderhoop** [comment]
thanks @imaginista!
