### ISSUE TITLE
Submit PR adding RemoteRetro to the awesome-react Applications list

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#321]
As a product owner,
I want RR listed in [awesome-react](https://github.com/enaqx/awesome-react#real-apps)
So that react developers have an additional way of finding the application.

__By Way Of Explanation:__ we recently got added to `awesome-phoenix`, and it's resulted in a number of people finding their way to our repo. And the best SEO metric is how many sites *link* to your site. So let's make sure we're getting ourselves linked to on awesome-react.

__Acceptance Criteria:__

- [x] PR is submitted to `awesome-react` in the *Real Apps* section, linking to our repo, and the live app, as seen in the [awesome-phoenix repo](https://github.com/droptheplot/awesome-phoenix#awesome-phoenix)

**Comment by tnewell5** [comment]
![image](https://user-images.githubusercontent.com/8727588/33441002-9308f64e-d5bf-11e7-9f59-cc33ed7f5727.png)
