### ISSUE TITLE
Submit PR adding RemoteRetro to the awesome-semantic-ui Applications list

### ISSUE THREAD

**Issue by tnewell5** [stride-nyc/remote_retro#323]
As a product owner,
I want RR listed in [awesome-semantic-ui](https://github.com/websemantics/awesome-semantic-ui)
So that react developers have an additional way of finding the application.

__By Way Of Explanation:__ we recently got added to `awesome-phoenix`, and it's resulted in a number of people finding their way to our repo. And the best SEO metric is how many sites *link* to your site. So let's make sure we're getting ourselves linked to on awesome-semantic-ui.

__Acceptance Criteria:__

- [x] PR is submitted to `awesome-semantic-ui` in the *Examples* section, linking to our repo, and the live app, as seen in the [awesome-phoenix repo](https://github.com/droptheplot/awesome-phoenix#awesome-phoenix)

**Comment by tnewell5** [comment]
![image](https://user-images.githubusercontent.com/8727588/33397824-e64f5b5e-d51a-11e7-8cc5-5f922a79ac0e.png)

**Comment by vanderhoop** [comment]
donesies!
