### ISSUE TITLE
Upgrade react-css-transition-replace to 3.x

### ISSUE THREAD

**Issue by tnewell5** [stride-nyc/remote_retro#327]
As a developer,
I want to utilize the most current version of react-css-transition-replace,
So that I can take advantage of the most recent features.

__Acceptance Criteria:__

- [ ] react-css-transition-replace is upgraded from 2.x -> 3.x
- [ ] the <ReactCSSTransitionReplace> component retains current behavior in app (vertical height does not get distorted or component does not become oddly jumpy when entering ideas or re-loading page during idea-generation or action-items stages.

**Comment by vanderhoop** [comment]
closing due to atrophy
