### ISSUE TITLE
Tweak to the guidelines language

### ISSUE THREAD

**Issue by Trevoke** [stride-nyc/remote_retro#330]
"Don't blast anybody" could be something like "assume good intent; mention only the impact of an action."

**Comment by vanderhoop** [comment]
Hey @Trevoke!

A) thanks for creating this issue. I wrote most of the guideline copy in a fever state, and while I know there's a lot of time for improvement, I haven't actually made time to tighten it up. Any and all suggestions are welcome. @singerguy0 I invite your feedback as well, as this seems like an issue you could supply suggestions for
B) is the thinking with the tweak above that we should stay away from "Don't"s in favor of  "Do"s?

**Comment by vanderhoop** [comment]
hey @Trevoke, tried a few things here, and ended up settling on "Assume best intent; you're all here to improve." Going to close for now, but feel free to re-open if you think it can be improved.
