### ISSUE TITLE
Drag and drop retro cards

### ISSUE THREAD

**Issue by sgleske-ias** [stride-nyc/remote_retro#336]
As a person,
I want to drag and drop cards across happy/sad/confused categories because, as a human, I'm prone to changing my mind on a whim.

__Acceptance Criteria:__

- [x] Cards I create can be arbitrarily dragged and dropped to other happy/sad/confused categories so I can flexibly change my mind.

**Comment by vanderhoop** [comment]
hey @sgleske-ias, thanks for creating this issue! Literally just merged a PR about 10 minutes ago that allows users to edit the category of their idea via drop down. It's deployed, so you should check it out. I'll leave this story open as an enhancement, as we'll likely want to allow drag and drop in the future, just as that's what many users have intuitively expected when wanting to recategorize. Thanks again!

**Comment by vanderhoop** [comment]
hey @sgleske-ias! Ideas are now draggable in the idea-generation stage by their authors (or facilitators, matching the current edit permisions), but are locked in the stages thereafter! Let us know whatcha think! And thank @ianmcnally for taking this on!

**Comment by sgleske-ias** [comment]
We just used today for the first time as a team.  Thanks for that @vanderhoop.  We'll be opening issues/feedback as we use it more.  Overall, retro was a positive experience ("the best retro we've had").

**Comment by vanderhoop** [comment]
hey @sgleske-ias! Glad to hear the tool provided value for you and your team! Let us know of any feature requests or issues you experience!

Also, gonna close this particular ticket, but i'll be added some UX enhancement tickets (cursors, drag target hover effects) in the near future!
