### ISSUE TITLE
urgent: upgrade Heroku Postgres from hobby plan -> standard plan

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#337]
As a developer,
I want to upgrade RR's Heroku Postgres plan from hobby to standard,
So that RemoteRetro, which relies on postgres, doesn't fail due to hitting our row limit.

__By Way Of Explanation:__ at the moment, we're on [Heroku Postgres](https://devcenter.heroku.com/articles/heroku-postgres-plans)' "hobby" plan. This was an excellent plan to start, however the "hobby" plan is limited to 10,000 rows, a limit which we are about to hit, with bad consequences:

![image](https://user-images.githubusercontent.com/4386645/33839700-2fbd18ce-de50-11e7-8a27-428302cf8396.png)

__Acceptance Criteria:__

- [ ] RemoteRetro is running successfully on Heroku Postgres' "standard" plan

__Helpful Links:__

- [Heroku Postgres Plans](https://devcenter.heroku.com/articles/heroku-postgres-plans)
- [Upgrading Heroku Postgres Plans](https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrade-with-follower-changeovers)

**Comment by samdec11** [comment]
@vanderhoop It looks like only you have the power to do this upgrade:
![screen shot 2017-12-12 at 1 46 16 pm](https://user-images.githubusercontent.com/2918454/33902409-e929e736-df42-11e7-8ab1-995a77d327da.png)

(we were following Heroku's instructions [here](https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#1-provision-new-database))

**Comment by samdec11** [comment]
We created a new db on the Standard-0 plan, copied all the data from the Hobby db over, and promoted the new db to become the primary one. Once we're sure everything is working as expected, we can delete the old one.
![screen shot 2017-12-18 at 5 28 40 pm](https://user-images.githubusercontent.com/2918454/34131360-48bc91e6-e419-11e7-8773-25c61f5aadee.png)
