### ISSUE TITLE
deploy an instance of RemoteRetro to Gigalixir

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#349]
As a developer,
I want to deploy RemoteRetro to [Gigalixir](https://gigalixir.com/),
So that we can fully leverage elixir's power.

__By Way Of Explanation:__ when we first developed RemoteRetro, the quickest and easiest way to get it deployed was via Heroku. Unfortunately, Heroku [has a handful of limitations when it comes to Elixir](https://hexdocs.pm/phoenix/heroku.html#limitations), including a connection limit for channels.

I have spoken with @jesseshieh, founder of Gigalixir, about the platform, and @erikreedstrom, a lead dev at [HomePolish](https://www.homepolish.com/), about his experience with Gigalixir, and I've come away feeling that Gigalixir is a strong fit for RR, as this will a) keep us from hitting Heroku's websocket connection limit, and b) allow us to leverage features of Elixir that are currently unavailable to us in production.

__Acceptance Criteria:__

- [x] instance of remote retro is deployed to Gigalixir

__Helpful Links:__

- [gigalixir.com](https://gigalixir.com/)
- [gigalixir docs](https://gigalixir.readthedocs.io/en/latest/)

**Comment by jesseshieh** [comment]
Let me know if there's anything I can do to help!

**Comment by vanderhoop** [comment]
hey @jesseshieh, not sure if you were serious about having time to open a PR with the necessary configs/boilerplate, but if you were, we'd certainly appreciate it!

**Comment by jesseshieh** [comment]
No problem! I'll start on it tomorrow.

**Comment by vanderhoop** [comment]
thanks, @jesseshieh!

**Comment by jesseshieh** [comment]
I just submitted https://github.com/stride-nyc/remote_retro/pull/351, but it doesn't work yet. Just linking this issue with it.

**Comment by vanderhoop** [comment]
closing, as implemented!
