### ISSUE TITLE
Landing Page Development Part 1: Upper Third Responsive Layout

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#358]
As a product owner,
I want the first section of the responsive landing page to be implemented
So that first-time users are more inclined to sign up for RR.

__Full Width:__ (living design available [here](https://www.figma.com/proto/rNfx2CqJ5l8iHmeQq4G3Ne/Landing-Page?scaling=contain&node-id=0%3A381&redirected=1))
___

![image.png](https://images.zenhubusercontent.com/55db27314f7a08fbb7f479a8/67688a41-dcce-407b-836e-110efdf4ac11)

__Mobile:__ (living design available [here](https://www.figma.com/proto/rNfx2CqJ5l8iHmeQq4G3Ne/Landing-Page?scaling=contain&node-id=35%3A2&redirected=1))
___

![image.png](https://images.zenhubusercontent.com/55db27314f7a08fbb7f479a8/dba13ba1-9e68-4c37-885b-2161c6b2600b)

__By Way Of Explanation:__ months back, @imaginista and @nonlinear threw together a landing page for RR. It did the job for the time being, but we're prioritizing making the landing page sexier to lower our bounce rate. We'll do this layout work incrementally, as much of the copy and design still needs to be worked out and iterated upon. 

__Acceptance Criteria:__

- [ ] First section of landing page is layed out in a responsive manner using SemanticUI classes
  - __Note:__ this story does not require pixel perfection. Use SemanticUI button styles and typography for consistency with the application. What's most important is that the responsive layout is in place and ready to be extended.

__Helpful Links:__

- [@nonlinear's design](https://www.figma.com/proto/rNfx2CqJ5l8iHmeQq4G3Ne/Landing-Page?scaling=contain&node-id=0%3A381&redirected=1)
  - __Note:__ you can see the mobile view by navigating to the right several times
  - __Note:__ we don't have the green light to use the communal text bubble logo. Just omit it!
- [SemanticUI Grid](https://semantic-ui.com/collections/grid.html)
- [SemanticUI Grid Definitions](https://semantic-ui.com/collections/grid.html#/definition)
- [SemanticUI Button](https://semantic-ui.com/elements/button.html)

**Comment by ianmcnally** [comment]
I was looking at Semantic's implementation of a "grid", and noticed it relies on flex box, which is good for a single direction layout, but involves some hacks for two dimensional layouts.

 If anyone's familiar with grid layouts, and it wouldn't disagree too much with the technical direction of the project, I might suggest doing the layout with grid 😁 ([intro](https://css-tricks.com/snippets/css/complete-guide-grid/). Once you get the hang of it, it's pretty easy and very cool.

I'm more than happy to help out if someone picks this up, or the approach sounds 👌 .

**Comment by vanderhoop** [comment]
Hey @ianmcnally! I was under the impression that css grid wasnt supprted in all the major browsers, but I just peeped caniuse and turns out I was totally wrong. So it's totally up to the implementer. You want to take this on? :wink:

**Comment by ianmcnally** [comment]
you got it, homes. i was already experimenting with grid for the general layout. i was able to get rid of a lot of wrapping tags 😁

**Comment by vanderhoop** [comment]
nice, will assign you!

**Comment by ianmcnally** [comment]
@vanderhoop couple Qs when you're not soaking up the 🌞:

- I was writing in rem but noticed they didn't map with pixel values. Is that intentional? I was gonna set it to be 10:1, but I don't want to mess up other rules. Should I use px or figure out the rem conversions?
- Should a logged in user get the same page, with the change in wording?
- With those semantic buttons, I was using basic & primary, which get the font color and border, but a transparent background (and !important rules that were hard to override). So I ended up writing the styles myself. We can dig into the specifics in review, but was wondering if I was missing something in Semantic?
- What's the diff between app.html.eex and index.html.eex? (The latter is where I've been making changes, but app looks like it contains something similar things)

Preview:

![rr-preview](https://user-images.githubusercontent.com/1494758/35174333-fde485ce-fd3c-11e7-89c9-f07bed719110.gif)

**Comment by vanderhoop** [comment]
hey @ianmcnally. apologies for the delayed response.

> I was writing in rem but noticed they didn't map with pixel values. Is that intentional? I was gonna set it to be 10px: 1rem, but I don't want to mess up other rules. Should I use px or figure out the rem conversions?

It was not intentional. Just peeped semantic source, and looks like the base size is 14px/1em/rem. We're trying (though we haven't succeeded) in only using `rem`, so leave the styles in rem for now, but no need to do exact calculations provided rounding doesn't _completely_ b0rk the layout.

> Should a logged in user get the same page, save the change in wording?

Yarp! The only changes in copy are seen in [the conditional render here](https://github.com/stride-nyc/remote_retro/blob/4e0c1c5e452cae39b61cd03c0865e3d0e271a158/web/templates/page/index.html.eex#L8-L26). I _think_  the layout should accommodate those copy changes just fine, but if you think we should alter the layout at all at a particular screen size (to better suit the content), I trust your judgement.


> With those semantic buttons, I was using basic & primary, which get the font color and border, but a transparent background (and !important rules that were hard to override). So I ended up writing the styles myself. We can dig into the specifics in review, but was wondering if I was missing something in Semantic?

I think you might be able to pass a `ui white button` to get the background for free, but not sure if that gives ya the text-color, so a mix and match of SemanticUI class and raw styles might be necessary. That said, we should encapsulate that mix for re-use elsewhere


> What's the diff between app.html.eex and index.html.eex? (The latter is where I've been making changes, but app looks like it contains something similar things)

`app.html.eex` is the the application layout, providing the html document boilerplate and wrapping elements to be served on every (non-ajax/non-websocket) request, while `index.html.eex` is the actual content of the `/`, so you're on the right track.

**Comment by vanderhoop** [comment]
closing, as we've decided to go another direction
