### ISSUE TITLE
unexpected: lose facilitatorship when I refresh

### ISSUE THREAD

**Issue by Trevoke** [stride-nyc/remote_retro#361]
We just had a retro where we came up with a few action items but the facilitator accidentally closed the tab before sending the email. When he reopened the tab with Cmt-T (or Ctrl-T or whatever your keyboard shortcut is for it), the button was gone. Adding a new action item did not bring it back.

**Comment by vanderhoop** [comment]
hey @Trevoke. those controls are scoped to the facilitator, and our current (perhaps absurd) way of determining who the facilitator is based on tenure in the room. Basically, it's ephemeral based on `Phoenix.Presence`. I need to groom some short-term and long-term fixes for this, but as a bandaid, you should be able to revisit the retro link and, provided you're the only one present, send out your retro's action items.

**Comment by vanderhoop** [comment]
hey @Trevoke, just prioritized #191 as the first in a number of stories surrounding facilitation transfer (including a grace period in which the facilitator can return)

**Comment by vanderhoop** [comment]
hey @Trevoke, removed the opaque business rule that the facilitator is the longest-tenured presence.  now it's just whoever created the retro. and we'll be prioritizing explicit facilitatorship transfers in the near future!

**Comment by vanderhoop** [comment]
closing, as this was implemented!
