### ISSUE TITLE
add 'required' indication beside 'Assignee' field in action-items stage

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#368]
As a user in the action items stage,
I want to be informed that the assignee field is required,
So that I'm not confused as to why the 'Submit' button is disabled.

__By Way Of Explanation:__ users must select an 'assignee' for an action item before the action item can be submitted, but at the moment, they need to figure this out themselves, as the 'Submit' button is disabled until the body and assignee fields have values.

__Example:__
![image](https://user-images.githubusercontent.com/4386645/34953274-a52b0e00-f9d9-11e7-8608-8b79d508a918.png)

__Acceptance Criteria:__

- [ ] there is a red asterisk in superscript beside the 'Assignee:' label in the action-items stage

__Helpful Links:__

- [SemanticUI Forms#required](https://semantic-ui.com/collections/form.html#required)
- [SemanticUI Input](https://semantic-ui.com/elements/input.html)
- [SemanticUI Label](https://semantic-ui.com/elements/label.html)

**Comment by vanderhoop** [comment]
dev note: I tried just adding the 'required' class to the label field within the Chrome inspect, as seen at SemanticUI's [required form field docs](https://semantic-ui.com/collections/form.html#required), but it seems borked, possibly due to the label being an inline label?

![image](https://user-images.githubusercontent.com/4386645/34953756-0a7474b2-f9db-11e7-81f7-bf211820bbc4.png)

**Comment by tnewell5** [comment]
hey @vanderhoop should we also have the required asterisk displayed next to the 'Category' label since it's also required?
![image](https://user-images.githubusercontent.com/8727588/35241108-6e818500-ff83-11e7-8297-8c64966d97eb.png)

**Comment by vanderhoop** [comment]
hey @tnewell5, no need to add it beside the "Category" label, as it's related input field has a default value, where the "Assignee" label's input does not

**Comment by tnewell5** [comment]
okay - I just thought that by adding it beside "Category" label, the participants would pay more attention to the idea classification and won't need to then take time to reclass. I'll go ahead and remove though.
