### ISSUE TITLE
introduce mix db tasks

### ISSUE THREAD

**Issue by caporta** [stride-nyc/remote_retro#37]
As a developer who would like to access the application databases,
I would like to type a single terminal command that provides me access to a given database environment,
so the implementation details of accessing the db are abstracted away.

__Acceptance Criteria:__
  - upon entering `mix db` in bash, the developer is thrown into the psql interface, pre-connected to the `remote_retro_dev` database
  - upon entering `MIX_ENV=staging mix db`, the developer is thrown in the psql interface, pre-connected to the staging db

**Comment by vanderhoop** [comment]
hey @caporta, added the acceptance criteria for the default task, which would take you to the dev database, but before I add criteria (or an entirely diffenent story) for connecting to other environments, which do you prefer for, say, connecting to the staging db?

```
MIX_ENV=staging mix db
```
OR

```
mix db.staging
```

The former is more idiomatic, mix-wise, but the latter avoids the need to always write out "MIX_ENV=". Thoughts?

**Comment by caporta** [comment]
I tend to think the former is slightly more brainfart-proof – I feel like there's a bit more cognitive overhead in having to prefix an env var to a command, which can be a good guard for mission-critical scripts like database tasks.

That said, it's largely six of one, half dozen of the other, and there is precedence already with commands like `mix test.watch`. I think both work, but my vote would be for `MIX_ENV=`

**Comment by vanderhoop** [comment]
dig. i'll update the acceptance criteria such that the mix_env maps you to the right db

**Comment by vanderhoop** [comment]
closing due to atrophy. happy to reopen at later date
