### ISSUE TITLE
UI Bug — Overlapping member queue

### ISSUE THREAD

**Issue by caporta** [stride-nyc/remote_retro#370]
The following UI bug was brought to Joor Stride team's attention in the 01/17/2018 retrospective. By changing the browser's vertical window height to `< ~530px` the user can cause an overlap between the member footer and the text boxes above (e.g. screenshot). a possible solution could maybe be providing a max height to the page container.

![image](https://user-images.githubusercontent.com/10603933/35066961-56f98e6e-fba0-11e7-98e4-1ab5c2fb0210.png)

**Comment by ianmcnally** [comment]
if y'all like the grid direction when #358 is done, we should talk about this page. a grid layout could handle height changes nicely. inspirational vid: https://www.youtube.com/watch?v=EEOJZy_Gge4

**Comment by vanderhoop** [comment]
@caporta @ianmcnally this issue got me thinking, and i'm curious, from a product standpoint, what do you think about just not showing the users list on mobile (and on a regular screens using brought down to mobile screen heights)? my feeling is that the real estate should be devoted to the idea board and idea input form.

**Comment by vanderhoop** [comment]
@caporta @ianmcnally I'm gonna close this as a wontfix for know, as it just doesn't feel valuable to fix relative to other open issues, but if either of ya want to make a case, do so!

**Comment by ianmcnally** [comment]
@vanderhoop would you be in to a hide/show for participants? when i've been facilitating, i'll usually manually delete the dom node, to give some more space

**Comment by vanderhoop** [comment]
@ianmcnally Hell yeah. That's a great idea! Can you create a story and I'll augment it with the design elements. Thanks!

**Comment by ianmcnally** [comment]
You got it, brody. https://github.com/stride-nyc/remote_retro/issues/408
