### ISSUE TITLE
disable facilitation transfer alerts in 'closed' stage

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#376]
As a user who receives the facilitatorship during the 'closed' stage of a retro,
I do not want to be alerted to the transfer,
So that I am not bothered with useless information.

__By Way Of Explanation:__ this story is a small but crucial enhancement to the work outlined in #191, as transfers of facilitatorship (current determined by tenure in the retro) are most likely to happen in the 'closed' stage, due to the often rapid departures of users at the close of a retro. At the moment, there is the potential for each remaining user to be alerted to their new role as facilitator, even though there is no reasonable action can be taken during the 'closed' stage. We don't want to alert our users unnecessarily!

__Acceptance Criteria:__

- [x] when there is a facilitation transfer in the 'closed' stage, the user who would receive the facilitation transfer alert *doesn't* get alerted

**Comment by vanderhoop** [comment]
(will remove the blocked label when #373 gets merged)

**Comment by vanderhoop** [comment]
no longer blocked!

**Comment by laumontemayor** [comment]
@vanderhoop PR for this: https://github.com/stride-nyc/remote_retro/pull/380

**Comment by vanderhoop** [comment]
implemented! closing!
