### ISSUE TITLE
optimistic UI updates when submitting ideas/votes

### ISSUE THREAD

**Issue by williamcodes** [stride-nyc/remote_retro#401]
As a user,
I want my votes and idea submissions to show up right away even with a bad connection
So that I don't vote or submit an idea twice thinking it hasn't gone through yet.

**Comment by vanderhoop** [comment]
relevant for whoever ends up taking this on: https://egghead.io/courses/optimistic-ui-updates-in-react?utm_source=drip&utm_medium=email&utm_content=react&__s=hwa5s63ct5qpr8fbiczk

**Comment by vanderhoop** [comment]
done!
