### ISSUE TITLE
ensure consistent elixir versions across dev machines

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#403]
As a developer,
I want my local elixir to align with the version used by other developers,
So that elixir version discrepancies are never even a consideration.

__By Way Of Explanation:__ when we started the project, the two means of managing elixir versions were still somewhat immature. a year has passed, and though we haven't been bitten yet, it'd be irresponsible to think we won't be someday.

__Acceptance Criteria:__

- [x] Decision is made between kiex and asdf-vm for version manager of choice
  - or potentially using docker images?
- [ ] `README.md` is updated with elixir version manager instructions (using elixir 1.5.0 to start, as this will align with the elixir version designated in `.tool-versions`, as this is what our CI and production environments pull from)

__Helpful Links:__
- [Docker Elixir](https://hub.docker.com/_/elixir/)
- [kiex version manager](https://github.com/taylor/kiex)
- [asdf version manager](https://github.com/asdf-vm/asdf)
- ~[exenv](https://github.com/exenv/exenv)~
  - __Note:__ looks like exenv isn't maintained

**Comment by dplain90** [comment]
@vanderhoop 

I used kiex and it was pretty seamless, very rvm/nvm esque. Where I had trouble was changing the Erlang version. There's a package called evm which is supposed to be a version manager for it, but it's clunky and in the end didn't work. Not sure if you know of any alternatives to suggest on that..

**Comment by vanderhoop** [comment]
@dplain90 , funny you should ask about this. I haven't used kiex myself, but I started playing around with this issue once @dholdren surfaced his troubles with elixir 1.6 in #477, and wanted to get us on a proper version management tool out of a deep, deep shame. got a branch to what I _think_ is a good place, locking us into particular erlang/elixir/hex versions with the asdf version manager, but only having other folks run the script on there machines will really tell. You can peep the diff [here](https://github.com/stride-nyc/remote_retro/commit/b255979b16f5f74706e93981d99688af432dd246) if interested

**Comment by vanderhoop** [comment]
addressed in 6d3fd7732b97a99c83c550d6e8f53f98ec8fecf5. closing!
