### ISSUE TITLE
do not display action items in retro index by default

### ISSUE THREAD

**Issue by ianmcnally** [stride-nyc/remote_retro#409]
As a user who has taken part in retros for different teams,
I want the action items for retros at `/retros` to be hidden by default,
So that my current retro participants don't potentially see items relating to _other_ teams' retros.

__By Way Of Explanation:__ (optional)

I've facilitated retros for several different teams (product team, group of directors, etc.). When I log in to facilitate for one group, I see the action items for *every* group. I'd like the ability to either hide them by default, so I can choose what to show. Or have some sort of scoping so that only the current group's action items are shown.

__Acceptance Criteria:__

- [x] upon visiting `/retros`, the "Action items" for each retro listed are hidden upon page load, with a `chevron-left` SemanticUI icon indicating that they can be displayed with a click
- [x] upon clicking the `chevron-left` icon, the action items list is toggled between being visible and not. 

__Example:__
```
+-------------------------------------------------------+
|                                                       |
|   MY RETROS                                           |
|   ---------                                           |
|    - /retros/blAh873ndo                               |
|      - Action Items▾                                  |
|        - Kill Rockstars                               |
|        - Take out trash                               |
|                                                       |
|    - /retros/blAh873ndo                               |
|      - Action Items◄                                  |
|                                                       |
|                                                       |
|                                                       |
|                                                       |
|                                                       |
+-------------------------------------------------------+
```

__Helpful Links:__

- [SemanticUI Icons](https://semantic-ui.com/elements/icon.html#business)
  - search for `chevron-left`

**Comment by vanderhoop** [comment]
Hey @ianmcnally! Thanks a million for making this, as this issue has been on my mind as well. At the moment, there's nothing in our data model that concretely groups a set of users other than their mutual participation in a given retro, but those participations can change from week to week, and, on top of that, anyone who somehow gets ahold of a `/retros/:UUID` link can currently join a retro. My first thought is that this surfaces the need for a 'team' entity, as this would allow us to scope what retros/action items are shown to a given team.

That said, team creation introduces a some important UX decisions: 
  1. Where in the current application flow would team creation take place? I'm against making first-time users to have to go through the hoops of creating a team just to play around with the app, but maybe team creation could be an option at the end of any retro that _isn't_ associated with a team? 

Something like:
```
+-------------------------------------------------------+
|                                                       |
|                                                       |
|         Hey Bobby! Looks like you finished your       |
|         first retro with Bobby, Sally, Davis,         |
|         and Jamie. Want us to create a team for       |
|         you?                                          |
|                                  +-------------+      |
|               Yes, we're called  | |           |      |
|                                  | |           |      |
|               No.                +-------------+      |
|                                                       |
|                                                       |
|                                    +-----------+      |
|                                    |  Submit   |      |
|                                    +-----------+      |
|                                                       |
|                                                       |
+-------------------------------------------------------+                                                      
```

**Comment by vanderhoop** [comment]
Another option, and a lower-cost one at that, would be to _not_ list the action items on the retro index page, and instead list the names of users who took part. It would involve an extra click to get to the action items you want to see though, but I think it would deliver the value/privacy you're looking for?

**Comment by vanderhoop** [comment]
@ianmcnally yes, there are dozens of considerations for managing teams (relationships, permissions, which team does one default to, et cetera), so the lowest cost solution is the one you mentioned above. Updating the criteria to reflect this.

**Comment by vanderhoop** [comment]
yo @ianmcnally, the lightweight solution discussed has been implemented and deployed. got to pair on it with our boy @kpthomas 💯

**Comment by ianmcnally** [comment]
Dream team alert 🚨 🎉 🚨

**Comment by vanderhoop** [comment]
implemented!
