### ISSUE TITLE
Add an Idea.changeset validation for the presence of an assignee_id when category is "action-item" 

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#413]
At the moment, we enforce the selection of an assignee during the `"action-items"` stage, but this is only on the front-end. We never added the accompanying validation on our `Idea` struct in the backend, and we should to account for folks who get cute and somehow, some way, find a way to submit ideas through some backchannel.

__Helpful Links:__

- [`Ecto.Changeset` docs](https://hexdocs.pm/ecto/Ecto.Changeset.html)

**Comment by samrrichards** [comment]
I just went through the setup process and would be happy to work on this issue when I get the chance!

**Comment by vanderhoop** [comment]
hey @samrrichards, that would be a great help! thanks! let us know if you run into any issues! updated the ticket with the docs for Ecto changesets

**Comment by samrrichards** [comment]
Great, will do!

**Comment by codyduval** [comment]
I'll take this since it's been sitting for a bit.
