### ISSUE TITLE
toggle ability to submit action items

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#43]
As a retro participant who doesn't want to submit action items until all of the ideas are on the board,
I want to be able to toggle the display and ability to submit action items,
So that I can focus on idea generation until I'm ready to move on.

__Pre-Reqs:__
  - completion of [allow users to submit action items](https://github.com/vanderhoop/remote_retro/issues/38)

__Acceptance Criteria:__
  - [x] a new SemanticUI "toggle" checkbox exists on the bottom right corner of the viewport, displayed inline with the idea submission form. Its label reads: "Toggle Action Items"
  - [x] the `action-item` select option from #38 no longer exists
  - [x] when the checkbox is in its default 'off' state, the `@action-items` column from #38 is not displayed
  - when the checkbox is in the 'on' state:
    - [x] the `@action-item` column is displayed alongside the other columns
    - [x] the `category` select field is not visible
    - [x] all submitted ideas go directly to the `@action-item` column

__Helpful Docs:__
  - [Semantic UI Checkbox](http://semantic-ui.com/modules/checkbox.html)

**Comment by tnewell5** [comment]
hey Travis! I'm making good progress on this story. Do you mind if I stay on it for a few more days? I will be coming to content night on Tuesday to work on it some more.

Thx!
Tanya

**Comment by vanderhoop** [comment]
hey @tnewell5, it's all yours!

**Comment by vanderhoop** [comment]
implemented long ago. closin!
