### ISSUE TITLE
notify facilitator if all votes are cast or not as an aggregate

### ISSUE THREAD

**Issue by williamcodes** [stride-nyc/remote_retro#435]
As a user,
I want an easy way to see if it's time to end the voting phase
So that I don't have to check all the vote cast statuses for participants, particularly in large groups where not all are visible at once.

__By Way Of Explanation:__ (optional)
Roberto Pedroso (lead eng for JOOR) requested this while running a retro

__Acceptance Criteria:__

- [ ] in the voting stage, when every user currently present in a retro has submitted all of their votes, a teal, Semantic UI 'pointing label' appears above the stage progression button, reading "All votes in! Let's move forward!"

__Should look something like this:__ 
![image](https://user-images.githubusercontent.com/4386645/42631832-58f755d2-85a9-11e8-900f-120f6b6e79e3.png)

__Helpful Links:__

- [Semantic UI Pointing Label](https://semantic-ui.com/elements/label.html)

**Comment by vanderhoop** [comment]
I think this is a great feature idea. We could prompt the facilitator to click "Proceed to Action Items" with a pointing tooltip that reads something like, "All votes in!", or remove the middleman and just progress the retro automatically once all participants have used up their votes. That might be a bit much; I don't know.

**Comment by vanderhoop** [comment]
example tooltip prompt: 

![image](https://user-images.githubusercontent.com/4386645/42631832-58f755d2-85a9-11e8-900f-120f6b6e79e3.png)

**Comment by vanderhoop** [comment]
hey @williamcodes. groomed this one! I'll throw it in the bench channel

**Comment by vanderhoop** [comment]
closing, as implemented by @pwjablonski in 8dfac0d
