### ISSUE TITLE
ability to mute the sound

### ISSUE THREAD

**Issue by hartzis** [stride-nyc/remote_retro#443]
As a participant,
I want to be able to mute the sound
So that while on a hangout I can turn off the noises.

__Acceptance Criteria:__

- [ ] \(able to mute sound while in a retro\)

**Comment by vanderhoop** [comment]
@hartzis! @CentroDL Closing this, as we killed the sound effects outright in https://github.com/stride-nyc/remote_retro/commit/d37a508e095db202b3faf5b36e3dbc65d6b29be7
