### ISSUE TITLE
make lobby guests wrap to multiple lines

### ISSUE THREAD

**Issue by williamcodes** [stride-nyc/remote_retro#453]
As a user
I want it to be more obvious that there are more users in the lobby than are visible
So that I don't delay starting because I think some people haven't joined yet

__By Way Of Explanation:__ 
This keeps confusing people at JOOR. We often have more participants than can fit on the screen. We often get first-time moderators and they never realize they can scroll. A simple fix would be allowing the list of faces to wrap to multiple lines when there are more profile picture thumbnails than will fit in a single line.

__Acceptance Criteria:__

- [x] the list of 'present' users wraps to multiple lines in the lobby and prime directive stage
   - see discussion below as to why we're scoping this wrapping to these stages

**Comment by vanderhoop** [comment]
Hey @williamcodes,
Would like to groom this a bit, but curious about the scoping of this change to particular stages. For example, the following would be fine in the lobby/prime directive stages, but the real estate would be a bit much in the idea generation stage:

___

![image](https://user-images.githubusercontent.com/4386645/42631560-80cf6262-85a8-11e8-97ea-fed119b130a2.png)

My thinking is that we could make this change in the aforementioned stages, and down the road implement some sort of "expand" feature on the user list in the other stages, leaving the side scroll behavior there for now. Does that make sense?

**Comment by williamcodes** [comment]
Yeah definitely, good thinking, I hadn't thought of the other stages of how
they would be impacted

**Comment by vanderhoop** [comment]
done thanks to @edem-ca!
