### ISSUE TITLE
react-hot-loader not working with modals

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#458]
As a developer,
I want our modal components to honor hot updates,
So that I don't have to refresh my browser and go through a bunch of manual steps to reproduce application state just to see changes made to our modal components.

__By Way Of Explanation:__ hot reloading works for all of our components except for those rendered as modals via `react-modal`. This is possibly due to an issue in the react-modal library, but I can only speculate.

__Acceptance Criteria:__

- [ ] making a copy change to the markup in `ShareRetroLinkModal` results in the immediate hot update to the modal on the screen.

#### What We've Verified Thus Far:

- the modal component files *are* being recompiled by webpack (we see the recompilation in the terminal).
- the hot update *is* reaching the application
  - you can reproduce this verification by
    - creating a new retro, verifying that the `ShareRetroLinkModal` is on the screen, then adding a `console.log("firing")` to the `ShareRetroLinkModal` component's `render` function, and checking the developer console, where you will see console output of "firing", originating from a hot update file.
- but updates that would affect the *markup* being updated don't take effect (at least, not to the eye)

#### Example Gif 

See the change to button configs results in a _working_ hot reload, following by a changes to the modal content, which _doesn't_ hot reload.
____

![hot_reloading_doesnt_work_for_modal](https://user-images.githubusercontent.com/4386645/42138311-e82e92d6-7d40-11e8-8ad7-54fe6e34dc60.gif)

**Comment by vanderhoop** [comment]
did some debugging on this:

```
what did i just learn?
  - that the modal component is render'ing on change of the file 
  - that ReactDOM.createPortal is getting called within Modal#render, so the issue is somewhere the portal call
```

**Comment by vanderhoop** [comment]
did more debugging, and figured out the issue. our components are being entirely unmounted and replaced with new instances (the constructor was being fired more than it should have), and the two stateful modal components have initial state of `isModalOpen: false`.

**Comment by vanderhoop** [comment]
i'm opposed to changing architecture (see previous comment about moving all modal state to the redux store) just to get hot reloading of several components. the issue is with React.createPortal reparenting the node, combined with the initial state issue mentioned above, and so if anything, we could introduce a component enhancer that, on unmount, saves the state, and if on the re-mount of the component (if `module(hot)` and the component props are the same), we could setState to the snapshot we saved. I don't know how I feel about that either. gonna stew on it.

**Comment by codyduval** [comment]
IMO, this seems like quite a bit of work for what is essentially a dev convenience.  But I can get how it must be a huge pain when working on a feature with a modal.

Given the two approaches you've identified above, moving the modal state into the redux store feels like the cleaner option.  But there are a lot of modals so each would need its own action and state.  It doesn't feel like the work is worth the benefit.

**Comment by vanderhoop** [comment]
yeah, those are all great points.  i'm cool closing.
