### ISSUE TITLE
allow users to log out

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#486]
As a signed-in user,
I want the ability to log out,
So that I can leave my computer alone without worrying about someone using my computer when I go to bathroom and looking at my action items.

__By Way Of Explanation:__ when we initially implemented login via google, we didn't add the corresponding log out feature. this was the quickest solution for allowing a personalized experience, but users have commented on the desire to log out to protect their privacy, and we should honor that.

__Acceptance Criteria:__

- [x] the 'built by stride' logo in the right hand corner of the header gets a sibling to the right,  a 'Log out' link
  - [x] upon clicking the logout link, the user's session is cleared and they are redirected to '/'
  - [ ] the button should only be visible when there is a current user

__Helpful Links:__

- [setting the user on session upon logging in](https://github.com/stride-nyc/remote_retro/blob/master/lib/remote_retro_web/controllers/auth_controller.ex#L10-L17)
  - [associated tests](https://github.com/stride-nyc/remote_retro/blob/master/test/controllers/auth_controller_test.exs)

**Comment by kamok** [comment]
You can assign this to me. Just got set up for dev.
