### ISSUE TITLE
deps: bump webpack 3.x -> 4.x

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#487]
As a developer,
I want to use the latest webpack major version,
So that I can use the latest features and documentation.

__By Way Of Explanation:__ webpack 4.x was released back in February, and we've punted on upgrading, but the docs have moved on, and there are features and performance benefits to migrating.

__Acceptance Criteria:__

- [x] the following npm scripts execute successfully using webpack 4:
  - `compile-dev`
  - `compile-production`
  - `watch`
- [x] if any of our current dependencies can be removed as a result of the migration, they are removed from `package.json` && `yarn.lock`
- [x] react-hot-module replacement still works when using `mix` (which calls `npm run watch` under the hood)

__Helpful Links:__

- [Webpack Doc on Migrating from 3.x -> 4.x](https://webpack.js.org/migrate/4/)

**Comment by iffj** [comment]
@vanderhoop hey travis, could you assign this to me?

**Comment by vanderhoop** [comment]
taking this on due to a security vulnerability that's surfaced in webpack dev server, which needs to be bumped from 2.x to 3.x, and that doesn't webpack 3.x 😠, but webpack 4.x

**Comment by vanderhoop** [comment]
https://github.com/stride-nyc/remote_retro/commit/288b665210110efa7c823c6ff764718e2fc8e853
