### ISSUE TITLE
allow users to access stage breakdowns after they've closed out the stage change alerts

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#489]
As a user who would like to review the breakdown of a given stage,
I want a means of accessing said breakdown,
So that I can proceed confidently in the current sage.

__By Way Of Explanation:__ users often close out the 'Stage Change' alerts containing stage breakdowns/guidance, only to then want to be able to review the rules of the current stage, but there is currently no way of doing so. yet 😄 

__Acceptance Criteria:__

- [ ] there is a SemanticUI "question circle" icon in the upper right hand of the header, to the left of the 'Built by Stride' logo
- [ ] upon hovering over the "question circle" icon for a moment, the native HTML title reads, "Access Stage Information"
- [ ] upon clicking the "question circle" icon, the same alert modal content that's surfaced during stage changes is surfaced.
  - __Note:__ do not include the 'Stage Change: [CURRENT_STAGE]' header seen in the stage change alerts, as the user will already be there
- [x] __A Nice to Have:__ upon exiting out of the Stage Change alert, this icon fades in and out three times to draw the user's eye to it

__Helpful Links:__

- [Semantic UI Icons](https://semantic-ui.com/elements/icon.html)
- [React Portals](https://reactjs.org/docs/portals.html)
  - the header element exists outside the scope of our normal React component heirarchy. React 16.x exposes "portals" for dealing with elements outside of said hierarchy.
- [The 'alert' reducer case that surfaces stage change alerts](https://github.com/stride-nyc/remote_retro/blob/master/web/static/js/redux/alert.js#L11-L14) and the [StageConfigs](https://github.com/stride-nyc/remote_retro/blob/e410fe7c80e59fd0ad1bf4301469958f6df51ea9/web/static/js/configs/stage_configs.jsx#L21-L24) map that it consumes

**Comment by codyduval** [comment]
I've got some time in the mornings this week - I'll see if I can make some progress on this one.
