### ISSUE TITLE
migrate prod Gigalixir deployment from Google Cloud Platform (US-Central) to AWS east-1 

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#493]
Our current Gigalixir production deployment is on Google Cloud Platform, in the us-central region. Gigalixir recently added support for AWS on either coast, which is great, in that we use Amazon RDS in the east-1 region, and this allows us to keep our services entirely on AWS in the same region. 

- [x] create new gigalixir app using AWS
- [x] ensure all production credentials are added to new AWS deployment (db, send grid, et cetera)
- [x] ensure AWS deployment works from soup to nuts
- [x] update DNS to point to new instance
  - requires changing at namecheap, on gigalixir, and changing the new instance so that its google_oauth_redirect_uri points to remoteretro.org/blah/blah/blah
- [x] wait until DNS propagation has taken place (requests to remoteretro.org are hitting new service)
- [x] update Circle CI such that successful `master` builds push to the new remote repository

__Helpful Links:__

- [Gigalixir Docs on AWS/Google Cloud Platform](https://gigalixir.readthedocs.io/en/latest/main.html#can-i-run-my-app-in-aws-instead-of-google-cloud-platform)

**Comment by vanderhoop** [comment]
adding blocked, as we don't want to kick off the DNS change until friday night, so that it has the weekend to propagate

**Comment by vanderhoop** [comment]
done :)

**Comment by mcade** [comment]
Could you walk through the steps of setting up Amazon RDS to work with Gigalixir? There are instructions for using GCP [here](https://gigalixir.readthedocs.io/en/latest/main.html#how-to-manually-set-up-a-google-cloud-sql-postgresql-database) so I tried mimicking them as much as I could for AWS but am not able to connect to the db from Gigalixir.

**Comment by vanderhoop** [comment]
hey @mcade! RemoteRetro was initially deployed on Heroku (sitting atop AWS), and we kept our Heroku Postgres service when we migrated to Gigalixir (because Heroku Postgres rules). And we do so [by plugging in the full database url in prod](https://github.com/stride-nyc/remote_retro/blob/master/config/prod.exs#L25). (__Note:__ you can likely disregard the bizarre string interpolation syntax. That's necessary due to our use of Distillery in production.)

I can't speak to your specific situation without knowing the details, but I'd guess that you should be able to get the full database url and plug that in with `ssl: true`?
