### ISSUE TITLE
Desire for a single, unified yarn version

### ISSUE THREAD

**Issue by kamok** [stride-nyc/remote_retro#508]
As a developer,
I want not have yarn.lock change all the time
So that I achieve Git tranquility.

__By Way Of Explanation:__ (optional)
Right now, we do `npm install -g yarn`. Developers will have different versions of yarn which have may cause different outputs on yarn.lock

This adds a lot of unnecessary noise.

__Acceptance Criteria:__

- [ ] \(One yarn version\)

__Helpful Links:__

- [documentation link](http://example.com)

**Comment by vanderhoop** [comment]
hey @kamok, this would make for a better dev experience. curious if you had a particular idea for ensuring all devs have the same yarn version?

**Comment by kamok** [comment]
@vanderhoop Not entirely sure what you did, but I think this can be closed now.
