### ISSUE TITLE
When running e2e tests on High Sierra, get error: is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!

### ISSUE THREAD

**Issue by kamok** [stride-nyc/remote_retro#509]
As a developer,
I want to run e2e tests without spam
So that I can actually read my logs and debug my failing e2e tests.

__By Way Of Explanation:__ (optional)

MacOS update introduce a bug, reported on several unrelated GitHub repos and on the Apple forums. Other developers have simply silenced the output if it contains those words: see [example](https://github.com/processing/processing/commit/f512457c6e6034a1230161a01080ede5f431eebb).
We can probably do the same until Apple fixes their crap.

I cannot debug my e2e tests because I can't see my damn failures. This comes and goes.
![image](https://user-images.githubusercontent.com/9758567/47461958-1026e300-d7b0-11e8-8f20-eae4fbb29f7e.png)

__Acceptance Criteria:__

- [ ] \(Stop seeing the message\)

__Helpful Links:__

- [documentation link](http://example.com)

**Comment by vanderhoop** [comment]
closing as an issue with chromedriver
