### ISSUE TITLE
Feature request: Add ability to plus 1 an idea

### ISSUE THREAD

**Issue by jennysoup** [stride-nyc/remote_retro#513]
As a user,
I want to be able to plus 1 an idea that another user writes
So that I don't rewrite the same idea.

__By Way Of Explanation:__ Often when our team is adding ideas, we will have duplicate ideas. This then makes it more difficult for us to track voting on an idea if the votes are split between duplicate ideas. 

__Acceptance Criteria:__

- [ ] I want to be able to click a button on the idea to "plus 1" it.

**Comment by vanderhoop** [comment]
hey @jennysoup, thank you for cooking this up, but we're going to close this one as a wontfix, as users can vote on ideas as a means of supporting one, and we want to limit the complexity added to the app as much as possible!
