### ISSUE TITLE
upgrade phoenix 1.3 -> 1.4

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#519]
As a developer,
I want to upgrade to the latest version of phoenix
So that we can remove code put in place to prevent race conditions that have been fixed in the latest framework.

__By Way Of Explanation:__ there was a race condition for folks leveraging the `Presence` api that's [been fixed in 1.4](https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e#update-your-presence-javascript)

__Acceptance Criteria:__

- [ ] all relevant upgrade steps in the guide below have been accounted for

__Helpful Links:__

- [Phoenix 1.3 -> 1.4 upgrade guide](https://gist.github.com/chrismccord/bb1f8b136f5a9e4abc0bfc07b832257e)

**Comment by codyduval** [comment]
I'm working on this - I can't move any cards in ZenHub, but I'll update here when it's ready to go.
