### ISSUE TITLE
attribute an idea to a user

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#52]
As a retrospective participant,
I would like to know who submitted an idea,
So that I can ask them to elaborate on their idea.

__Acceptance Criteria:__

- [ ] ideas on the board are prefixed with `"<FIRST NAME>: "` where first name is the first name of whoever submitted the idea :)
- [ ] when a user enters a retro that already has ideas on the board, they can see the name of whoever submitted a particular idea
  - __Note:__ this involves persistence

__Example:__

```
┌─────────────┐
│      :)     │
├─────────────┤
│ sean: linter│
│ dan: linter!│
│ meg: linter!|
└─────────────┘
```

**Comment by caporta** [comment]
@vanderhoop I don't believe Acceptance Criterion #2 involves persistence now that we've gone the `presences[userToken]` route, but I could be wrong. Tested with ngrok and everything looks gravy.
