### ISSUE TITLE
ensure 'group' colors are always visibly distinct

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#544]
As a user in the grouping stage,
I want the grouping colors to be clearly distinguishable from one another
So that I don't have to squint to detect that the colors (and groups) are in-fact different.

__By Way Of Explanation:__ as a first pass in the grouping stage, [we're generating 'group' colors using the idea's `ephemeralGroupingId` as a seed](https://github.com/stride-nyc/remote_retro/blob/master/web/static/js/components/grouping_stage_idea_card.jsx#L71). This results in deterministic colors, but the generated colors are a) sometimes nextdoor neighbors on the color wheel, making them hard to distinguish between, and b) are sometimes lower contrast colors like yellow on our white background. This is a usability and accessibility concern, and so we have to fix it!

__Ejemplo!__

![Screen Shot 2019-08-13 at 6 36 47 PM](https://user-images.githubusercontent.com/4386645/63126420-19668380-bf6d-11e9-96d8-61fe42e50426.png)

__Acceptance Criteria:__

- [ ] group colors are always from [a colorblind friendly palette](https://venngage.com/blog/color-blind-friendly-palette/)
- [x] all group colors are visibly distinct from the rest
- [x] color generation is deterministic, i.e. given the same group id multiple times, the color generated is the same each time
- [x] nice to have: no light yellows! (it's low-contrast on our white background).

__Helpful Links:__

- [chroma.js Library](https://gka.github.io/chroma.js/)
  - has numerous color utilities, including the ability to creating colorblind-friendly palettes given different parameters
    - could be overkill for what we need, but who knows what the implementation will require

__Dev Note:__
- to turn on the grouping feature locally, you'll have to fire off `localStorage.setItem('groupingDev', true)`

**Comment by steven-solomon** [comment]
I wonder if you could define a rainbow gradient that you could use to look up a color by x,y coordinates. This would allow the position to be deterministic and guarantee colors next to each other don’t look similar.

**Comment by vanderhoop** [comment]
implemented!
