### ISSUE TITLE
Feature Request: Show retro item message fully during grouping

### ISSUE THREAD

**Issue by rebeccasiow** [stride-nyc/remote_retro#571]
As a retro participant grouping retro items,
I want to read the full retro item on each card
So that I can have more context into the retro item and can group it appropriately.

__By Way Of Explanation:__ 
During the grouping stage, each retro item card is truncated after 2 lines, making it difficult to tell which group it should belong to. This could be solved by expanding each card to show the full message, or adding a scroll within the box, or even making it have a draggable width! If there are concerns with really large retro items, there could also be a character limit(not that this happens often).

![Screen Shot 2020-05-27 at 5 26 08 PM](https://user-images.githubusercontent.com/10553889/83074483-3f629d80-a040-11ea-8847-4fe481af1ca6.png)

(Full message says: For newer members of the team, redefine purpose of each scrum event before starting to get alignment on how meeting time is spent and avoid wasted time.)

__Acceptance Criteria:__

- [ ] In the grouping phase, show the full message on each retro item.

**Comment by vanderhoop** [comment]
this is an excellent issue; thanks @rebeccasiow. Let's go with the scroll approach, as we need to maintain the limited real-estate on the grouping board.

**Comment by rebeccasiow** [comment]
YAY 😁
