### ISSUE TITLE
add mix task for running credo, the linter/static analysis tool for elixir

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#58]
As a developer who wants to know when I've deviated from the style guide,
I want to be able to run an elixir linter/static-analysis tool,
So that I know of any lint and opportunities for refactoring.

__Acceptance Criteria:__

- [x] running `mix credo` results in terminal output containing lint errors and opportunities for refactoring

__Documentation__
  - https://github.com/rrrene/credo

**Comment by Zanadar** [comment]
Tackling this one.

**Comment by vanderhoop** [comment]
implemented
