### ISSUE TITLE
Feature Request: Labeling face tab to next block

### ISSUE THREAD

**Issue by MakerTim** [stride-nyc/remote_retro#583]
As a facilitator,
I want to tab to the next Group label
So that I can label faster.

__By Way Of Explanation:__ (optional)
When I type the first label i want to switch faster to the next Label

__Acceptance Criteria:__
- [ ] \(After typing a label in the labeling fase, press [TAB] and now i'm typing in the next label\)

__Helpful Links:__

- [What is tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)

**Comment by MakerTim** [comment]
^ PR incoming later today, its not hard to implement

**Comment by vanderhoop** [comment]
closing, as we got the desired behavior for free when splitting labeling and voting into two distinct stages in https://github.com/stride-nyc/remote_retro/commit/06f3b0edff4f3283d355aeb86bdb793c0cb644fd
