### ISSUE TITLE
[BUG] 500 after redirection from `Sign in with Google` button

### ISSUE THREAD

**Issue by manumc** [stride-nyc/remote_retro#595]
I was able to select my google account and sign in but on redirection back to `https://remoteretro.org/` I got a 500.

It _fix_ itself by just reloading the page on the browser.

I was not able to reproduce it given that once you login you can only logout but not delete your own account. Seems like is something that only happens first time.

Hope this is helpful :heart:

**Comment by manumc** [comment]
PS. labels doesn't show up so I put it on the title

**Comment by omgitsbillryan** [comment]
This is happening again 😄 
![image](https://github.com/stride-nyc/remote_retro/assets/3077884/91f12387-cabd-4c5e-a494-54adbd58b650)

**Comment by omgitsbillryan** [comment]
I'm not able to fix it with a refresh, though 🤔

**Comment by mwytock0812** [comment]
Hi @omgitsbillryan, Google stopped sending us some required params on auth success, which was causing 500s. This should be resolved. Please reopen if you're still seeing this.
