### ISSUE TITLE
ensure webpack runs before end-to-end tests in `mix e2e`

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#61]
hey all, @williamcodes and @caporta run into some trouble running the `mix e2e` task, as webpack hadn't transpiled all the es6 goodness into a browser-digestable form. so we need to make sure that `mix e2e` either A) always run webpack (potentially an annoying extra 5 seconds to every test run), or B) checks to see if there's a compiled app.js file, and if there isn't, for webpack to run.

**Comment by Zanadar** [comment]
I just bit by this.  I had some old buggy javascript compiled from another branch that ran fine, but was causing failures.  When I did a `mix` it cleared things up. I think the re-compile is a good idea.

**Comment by vanderhoop** [comment]
implemented
