### ISSUE TITLE
bug: ideas with identical category + body combinations aren't rendered

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#64]
__Steps to reproduce:__

1. submit an idea of category "happy" with the body text of "bug!"
1. see it appear in the happy column
1. now submit another idea of category "happy" with the body text of "bug!"
1. the idea just submitted does not appear

__Hunch:__

Likely an issue with identical `key` values within the `CategoryColumn`'s list items?

**Comment by Zanadar** [comment]
Do we want to create some sort of IDs for ideas client side and persist them?  That'd maybe help this and make deletion easier....

**Comment by vanderhoop** [comment]
@Zanadar The ideas are persisted within the `RetroChannel`, we just don't pass the id back. I think if we passed the primary key back to the client, this issue disappears

**Comment by vanderhoop** [comment]
implemented
