### ISSUE TITLE
Bump phoenix 1.3

### ISSUE THREAD

**Issue by Zanadar** [stride-nyc/remote_retro#71]
Some big changes coming in Phoenix 1.3.  Do we want to track the new version?  Nothing breaking, but folder structure is changing and concepts are shifting.  No models, etc.

See http://swanros.com/phoenix-1-3-is-pure-love-for-api-development/

## Pro:

1. We move forward into the future!
2. Possibly generate content based on the new world?

## Cons

1. Documentation will be out of sync for a while
2. Confusion!

**Comment by adamtrilling** [comment]
This project is in an early enough phase that it's hard to justify not upgrading. Also, the Phoenix 1.3 directory layout is much more idiomatic Elixir.

**Comment by vanderhoop** [comment]
hey @Zanadar, i'm with @adamtrilling in that it makes sense to upgrade now while the codebase is still small, as it'll only get more difficult as time goes on. my current thinking is that we should just branch of master and have a `upgrade/phoenix-1_3` branch, that we can work off of, and merge when it's lived long enough that it has confidence

**Comment by joshuatrii** [comment]
Got started on this, there are a LOT of changes to the directory structure, but it seems reasonable. Should have a PR tomorrow.

**Comment by joshuatrii** [comment]
It's lit 🔥

**Comment by vanderhoop** [comment]
implemented!
