### ISSUE TITLE
mix mocha.watch (and possibly mix.mocha) b0rk the bash prompt on exit

### ISSUE THREAD

**Issue by crq** [stride-nyc/remote_retro#87]
Cursor dies 
![mochawatch](https://cloud.githubusercontent.com/assets/5898417/24174725/80d4a85c-0e68-11e7-9322-c32089778350.gif)

**Comment by vanderhoop** [comment]
@crq Removed the mix mocha task outright, as we're doing just fine using the `mocha` executable. closin'
