### ISSUE TITLE
allow facilitator to highlight an item on the board

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#94]
As a facilitator,
I would like to draw participants' eyes to a particular idea on the board,
So that the idea can be clarified and discussed without users having to scan the entire viewport.

__Acceptance Criteria:__

- [x] facilitators (and facilitators only) can hover over any idea and trigger the following styles:
  - the cursor should become `pointer` cursor
  - the idea's background should darken
- [x] upon clicking an idea:
  - [x] all connected clients (facilitator included) see a visual indication that the idea is focused
  - [x] the facilitator has some means of un-focusing the idea
      - [x] upon engaging the un-focusing mechanism, all connected clients have the idea unfocused

**Comment by vanderhoop** [comment]
blocked by the need for high-level design criteria from @imaginista. Brett: make sure you look through Semantic for ideas, as we have the entire library at our disposal

**Comment by imaginista** [comment]
- [ ] facilitators (and facilitators only) can hover over any idea and trigger the following styles:
the cursor should become pointer cursor 

![note-hover](https://cloud.githubusercontent.com/assets/1500663/24722651/88ed150a-1a12-11e7-9518-de52fe29a0eb.png)
the idea's background should darken

**Comment by imaginista** [comment]
- [ ] upon clicking an idea:
  - [ ] all connected clients (facilitator included) see a visual indication that the idea is focused

**Facilitator view:**
![note-edit](https://cloud.githubusercontent.com/assets/1500663/24722694/b8c69508-1a12-11e7-9952-ea6b29718307.png)

**Client view:**

![note-edit brett s view](https://cloud.githubusercontent.com/assets/1500663/24722716/c96cd1ec-1a12-11e7-89b7-659de139871f.png)

- [ ] the facilitator has some means of un-focusing the idea
      - [ ] upon engaging the un-focusing mechanism, all connected clients have the idea unfocused

**Comment by imaginista** [comment]
also, could have "controls" surface with facilitator view. leaving here for further discussion.

![note-hover-controls](https://cloud.githubusercontent.com/assets/1500663/24726252/accc7ab2-1a1f-11e7-9c27-f3be0f2084a2.png)

![note-hover-controls-breakdown](https://cloud.githubusercontent.com/assets/1500663/24726253/acccb518-1a1f-11e7-8f50-17734fffe22f.png)

**Comment by vanderhoop** [comment]
closing due to indirect completion in the facilitators edit story
