### ISSUE TITLE
allow facilitator to edit ideas

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#95]
As a facilitator,
I want to be able to edit an unclear or overlong idea,
So that all ideas are easily digested by participants

__Design Considerations:__

- [x] visual indicator that idea is editable
- [x] when the facilitator has clicked the edit icon, how does the interface react?
  - does the idea become an editable input in place?
  - does the idea auto-populate the idea input?
    - if we go this route, what happens if the facilitator already has an idea half-typed in the input

**Comment by vanderhoop** [comment]
adding blocked label until design/interaction criteria is fleshed out

**Comment by imaginista** [comment]
@vanderhoop might need to talk with you on this a bit more: 

"does the idea auto-populate the idea input?
if we go this route, what happens if the facilitator already has an idea half-typed in the input"

Not exactly sure what is meant.

**Comment by imaginista** [comment]
visual indicator that idea is editable:

In Facilitator view, all note submissions are selectable. Hover state is a vibrant color. 

![note-hover](https://cloud.githubusercontent.com/assets/1500663/24718611/afa293f4-1a04-11e7-9df3-10fe1d9e8487.png)

**Comment by imaginista** [comment]
"when the facilitator has clicked the edit icon, how does the interface react?"

- In Facilitator view, the note submission is presented in a floating window with border outline in same vibrant color as hover state (at 100% opacity). 
- Window communicates to facilitlar which person's note they are editing
- Changes must be saved to take effect
- Window does not allow off-focus window close - the user must select Cancel to exit without saving changes.
- Facilitator icon placed touching border of the window to communicate to rest of group what is happening

![note-edit](https://cloud.githubusercontent.com/assets/1500663/24718703/f607e934-1a04-11e7-96e1-ac659838352a.png)

**Comment by imaginista** [comment]
Not a part of this story, but this is how I would imagine the view to appear from a participant's perspective as the facilitator is editing the note:

![note-edit brett s view](https://cloud.githubusercontent.com/assets/1500663/24718906/c4ea8e6e-1a05-11e7-8909-5eae4c0997b5.png)

**Comment by vanderhoop** [comment]
implemented
